### ISSUE TITLE
Prenatal Register requires thicker horizontal scroll bar

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#102]
Please add a thicker horizontal scroll bar to the register view. 
![screenshot_2017-03-31-09-24-21](https://cloud.githubusercontent.com/assets/9537700/24559603/29c23122-15f4-11e7-8349-e09221776470.png)

**Comment by space-ravi** [comment]
The scroll bar you added is WAY too thick!  It needs to be visible but also pleasing to the eye. I would suggest trying about 30% of the height that you have.

**Comment by whppawan** [comment]
Done
