### ISSUE TITLE
Language mismatch

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#103]
When in French, if I go to the Register view, it is in English. Furthermore, when I click on a row to go to the patient summary, the component names are in English. See 2 screenshots below. 

![screenshot_2017-03-31-09-24-21](https://cloud.githubusercontent.com/assets/9537700/24559737/ac874c46-15f4-11e7-8511-358ca473aa6b.png)

![screenshot_2017-03-31-09-30-31](https://cloud.githubusercontent.com/assets/9537700/24559788/ddd8359e-15f4-11e7-84a8-5e67d66618ab.png)

**Comment by whppawan** [comment]
Done

**Comment by whppawan** [comment]
We have made some changes in admin. Now the options need their id separated with "-"

**Comment by space-ravi** [comment]
Not working for me. Make sure it is working with the admin being used for the field tablets before reassigning to me.

**Comment by whppawan** [comment]
Earlier we were entering the option like "Monthly number|File number" But now we need add id also. So we need to add the options in the following format -

Component Name-Component Id|Component Name-Component Id|Component Name-Component Id........
eg. Monthly number-183|File number-177

**Comment by whppawan** [comment]
I have also added some component's id in English and French languages and left other component as it was and its data will not appear in register screen. You can add the ids or I will add the remaining components' id tomorrow.
