### ISSUE TITLE
Back arrow on patient summary screen (from register) not working

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#104]
Steps: 
1. View Register
2. Click on a row to go to patient summary screen
3. Press back arrow

The app then goes to a broken screen. It should go back to the patient register. 

![screenshot_2017-03-31-09-46-05](https://cloud.githubusercontent.com/assets/9537700/24560295/083dc784-15f7-11e7-864a-c1b47b0fa6e4.png)

**Comment by whppawan** [comment]
Need to given the path of patient register.

**Comment by space-ravi** [comment]
Patient register is the "Patient Registration Report" screen.

**Comment by whppawan** [comment]
On back button onclick target was given for "patient visit" screen. Now i have changed it to "Patient Registration Report" screen.
