### ISSUE TITLE
Back arrow design on patient summary screen (via register)

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#105]
The back arrow on the patient summary screen (and all screens that have the back arrow) should have the following attributes. 

paddingTop:10|paddingLeft:30|paddingBottom:10|gravity:center|layoutGravity:center|bgColor:#3693b9|tint:#FFFFFF|ScaleType:FIT_XY|value:Backward|width:100

**Comment by whppawan** [comment]
Do we need to hard code it?
