### ISSUE TITLE
Keyboard pops up when clicking View Register

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#106]
When viewing the View Register screen, the keyboard comes up. Since there is nothing to enter, the keyboard should not show up on this screen. 

![screenshot_2017-03-31-10-00-25](https://cloud.githubusercontent.com/assets/9537700/24560774/f2a0e6ac-15f8-11e7-941b-78ff4ceaec0b.png)

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Still happening.

**Comment by space-ravi** [comment]
note to self: remove the search button.
