### ISSUE TITLE
Register screen sometimes blank

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#108]
After going from register view to the patient summary, then clicking OK, then going back to register view (and doing this a few times), the register view ends up blank (I did this in French language): 

![screenshot_2017-03-31-10-09-00](https://cloud.githubusercontent.com/assets/9537700/24561061/32d33f44-15fa-11e7-8dc5-3ef732592327.png)

**Comment by whppawan** [comment]
Done
