### ISSUE TITLE
Register screen doesn't fill screen

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#109]
On the Register screen, I can't get the table to fill the screen (even after updating the height attribute [here](http://103.225.41.0/ltfhcdynamic/admin/index.php?page=component&search_screen_id=30&start=&action=edit&id=155) to be a very large value like 2000. 

How can I increase the table height?

![screenshot_2017-03-31-10-22-16](https://cloud.githubusercontent.com/assets/9537700/24561685/8636aed0-15fc-11e7-9e0b-6e3fcbd0f312.png)

**Comment by whppawan** [comment]
Done
