### ISSUE TITLE
Report design

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#110]
The report design should look more like screenshot below. 
Things to point out: 
- No black column
- Every other row highlighted in light gray
- Header area is different, less wasted space
- I'll provide French and Swahili translations ASAP
- Back arrow will go back to Prenatal Main Menu screen

<img width="608" alt="screen shot 2017-04-01 at 1 01 34 pm" src="https://cloud.githubusercontent.com/assets/9537700/24582014/727e37a2-16db-11e7-9473-736f453c4e10.png">

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Ravi to add in backward arrow and change title
