### ISSUE TITLE
Drop down icon for report month

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#111]
The drop down icon for the report month looks fuzzy. Please use the attached icon from Google Material Design.

![ic_arrow_drop_down_black_24dp](https://cloud.githubusercontent.com/assets/9537700/24581924/c5619c04-16d9-11e7-957e-a0e3c800b6fb.png)

![screenshot_2017-04-01-12-50-28](https://cloud.githubusercontent.com/assets/9537700/24581932/ea052d32-16d9-11e7-8134-894fb2117f5c.png)

**Comment by whppawan** [comment]
Done
