### ISSUE TITLE
Report months in different languages

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#112]
The attached has the months in different languages. Please use this for the month menu on the report screen. Please spell out the month in its entirety (no abbreviations). 
Use the format: January 2017
(no dash necessary between month and year)

[months translations.xlsx](https://github.com/kamal1978/LTFHC/files/887917/months.translations.xlsx)

Use on this screen: 
![screenshot_2017-04-01-12-50-28](https://cloud.githubusercontent.com/assets/9537700/24581987/d3835790-16da-11e7-8589-4214aace8785.png)

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Please capitalize the months (like it is written in the spreadsheet above).

**Comment by kamal1978** [comment]
fixed
