### ISSUE TITLE
Issue logging into app

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#114]
When I try to log into the app using test/123, I get this error message (originally only happened when I changed the language to Kiswahili, now happening for all languages): 

![screenshot_2017-04-04-19-02-42](https://cloud.githubusercontent.com/assets/9537700/24686541/81854746-1969-11e7-9cbc-480217a23f7c.png)

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Now when I change the language, I keep getting an error for connection problems (despite being on very good WiFi):
 
![screenshot_2017-04-05-18-51-28](https://cloud.githubusercontent.com/assets/9537700/24734220/077790bc-1a31-11e7-8d33-d71f0747802e.png)
