### ISSUE TITLE
Back and Forward arrows not showing up on screens

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#118]
None of my back or forward arrows are showing up. This needs to be fixed ASAP.

**Comment by space-ravi** [comment]
Check if this is resolved when transferring all screens over.

**Comment by whppawan** [comment]
I have transferred the data. Back and forward buttons are now showing up.

**Comment by space-ravi** [comment]
Still happening intermittently.

**Comment by whppawan** [comment]
Done.
If the arrow is not being displayed in any of the screen look it in admin whether the image is being shown. If not then upload the image.
