### ISSUE TITLE
Unable to switch languages

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#120]
When I switch the language from English to French, I get stuck on this screen for several minutes. Sometimes the app is able to get passed the screen, sometimes not, and sometimes it crashes. 

![screenshot_2017-04-10-19-52-30](https://cloud.githubusercontent.com/assets/9537700/24890903/5addd5d2-1e27-11e7-9d32-8f5b14af5891.png)

**Comment by space-ravi** [comment]
Will not be an issue if we download all languages when the app first launches. See #123

**Comment by whppawan** [comment]
Resolve with issue 123
