### ISSUE TITLE
Kiswahili wordsmithing

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#125]
Please change the following text for Swahili (as requested by LTFHC): 

Login screen: 
- Change "New mtumiaji" to "Mtumiaji mpya"

Create new user screen: 
- Change "Jina mfanyakazi wa afya" to "Jina la kwanza la mfanyakazi wa afya"
- Change "Jina Health mfanyakazi" to "Jina la Pili la mfanyakazi wa afya"

**Comment by whppawan** [comment]
Done
