### ISSUE TITLE
Connectivity issue

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#126]
LTFHC keeps getting the "Connection Issue: Try Again" error while trying to login (or when pressing "Download" to download the latest off the server). 

However, the internet is working on the tablet for other apps (e.g. able to watch youtube videos). This issue is preventing Jessica from downloading the latest updates I made via the backend. Restarting the tablet, clearing the data, deleting/reinstalling the app do not help. The issue persists. 

This is happening on 4 tablets that LTFHC is using in the field at the moment. 

I've also experienced a similar issue before.

**Comment by space-ravi** [comment]
This is happening on 4 tablets that LTFHC is using in the field right now.

**Comment by space-ravi** [comment]
![img_5435](https://cloud.githubusercontent.com/assets/9537700/25053794/50146398-210e-11e7-898e-34b26d9f3dc5.JPG)

![img_5434](https://cloud.githubusercontent.com/assets/9537700/25053795/52a27d48-210e-11e7-9980-29d54726119b.JPG)

**Comment by space-ravi** [comment]
From Jessica: "Perhaps a clue: when I re-download the app from the playstore, it downloads IMMEDIATELY (never see the loading bar), which has never before been the case."

**Comment by whppawan** [comment]
This issue occurs when the server internet goes down.

**Comment by space-ravi** [comment]
We should talk about this again then. This is another example of having issues using the WHP server.
