### ISSUE TITLE
Register design issues

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#128]
Register not taking up full space on tablet. Also, vertical scroll bar only shows up if you scroll all the way to the right (it should always appear on the screen). Happening in all languages (but worse in French than in English). 

![screenshot_2017-04-14-10-03-04](https://cloud.githubusercontent.com/assets/9537700/25050108/5840980c-20fa-11e7-9206-ad71b36a727b.png)

**Comment by space-ravi** [comment]
Note that I am able to scroll down when the register is cut off, so this issue does not resolve itself when more patients are added. See attached screenshots: 

When I first go to register:
![1 screenshot_2017-04-24-19-26-54](https://cloud.githubusercontent.com/assets/9537700/25366411/5885249a-2924-11e7-8e14-3d3029e9eb8a.png)

When I scroll down on register:
![2 screenshot_2017-04-24-19-27-00](https://cloud.githubusercontent.com/assets/9537700/25366416/5c0fc43a-2924-11e7-8ba8-b7176bdc20af.png)

**Comment by space-ravi** [comment]
See screenshots in most recent comment for #131 for an example of this that happened today...

**Comment by space-ravi** [comment]
Still not working as expected. After entering a patient in English, I am required to scroll to see the information. The row should be sized to fit the data. 
![screenshot_2017-05-18-19-24-59](https://cloud.githubusercontent.com/assets/9537700/26230740/ff89c4ec-3bff-11e7-9c5e-e05d5c2a861f.png)

![screenshot_2017-05-18-19-25-08](https://cloud.githubusercontent.com/assets/9537700/26230742/038cf578-3c00-11e7-87aa-1504139405dc.png)

**Comment by kamal1978** [comment]
ok let me check on this

**Comment by kamal1978** [comment]
fixed app sent for testing
