### ISSUE TITLE
Health area design + crash

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#130]
I have the health area screen set to be a drop down list. When I select an option and press OK, the app crashes. Desire is to make this a **radio list** with the following: 

Column 1: 
Katondo|Tembwe|Kimena|Katibili|Kataki|Other

Column 2:
Undugu|M'toa|Kitoke|Rugumba|Wimbi

http://whpeportal.org/ltfhcdynamic/admin/index.php?page=component&search_screen_id=8&start=&action=edit&id=133

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Crash is fixed but this needs to be made a **radio list** instead of a dropdown list (see original comment). Also, if the user selects "Other" in this radio list, it should display a pop up (just like when "Other" is selected on other screens).

**Comment by whppawan** [comment]
Popup in "Other" case is pending.
