### ISSUE TITLE
Entered a patient into register, date showed up in wrong spot

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#131]
After entering a patient into the register, the date, file number, and monthly number showed up in the wrong columns (shifted one to the right). See screenshot. I am attempting to upload this data in case it's helpful (but upload is stuck on status bar). 

![screenshot_2017-04-16-21-01-08](https://cloud.githubusercontent.com/assets/9537700/25078486/1ced4f62-22e8-11e7-9d0d-aad27ad0eb97.png)

**Comment by space-ravi** [comment]
Closing without any action. See if this comes up again.

**Comment by space-ravi** [comment]
Happened again, see screenshots:
I entered 2 patients into the register. The first one, Anjaly, worked ok. The second one, Karishma, has her data shifted. 

![screenshot_2017-04-26-20-35-00](https://cloud.githubusercontent.com/assets/9537700/25466896/1a898e5e-2ac0-11e7-9337-992e2340ff81.png)

![screenshot_2017-04-26-20-34-56](https://cloud.githubusercontent.com/assets/9537700/25466897/1e547c4c-2ac0-11e7-8db2-72694e39fb86.png)

**Comment by space-ravi** [comment]
Happened again today in French language. See screenshot. I can't upload my data to show you because issue #132  
![screenshot_2017-05-02-20-41-05](https://cloud.githubusercontent.com/assets/9537700/25647542/c50300f2-2f77-11e7-8995-23d89b2725c9.png)

**Comment by space-ravi** [comment]
I'm curious, did you actually do something to fix this issue, or are you not able to replicate so you are calling this closed?

**Comment by kamal1978** [comment]
Ravi we did some changes in the populations of fields in the report, which were we saw was hey wire, this fix may or may not directly impacted this issue. Lets keep a watch, open it again once you face this problem

**Comment by space-ravi** [comment]
Sounds good

**Comment by space-ravi** [comment]
I found this issue again. Running v0.33 APK file (not from play store). See attached. I uploaded data. 
![screenshot_2017-06-23-13-51-49](https://user-images.githubusercontent.com/9537700/27500041-6e79ebac-581b-11e7-822f-43a5fd8808dc.png)

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Did you find an issue?

**Comment by whppawan** [comment]
Yes, We found and resolved it.
