### ISSUE TITLE
Unable to upload data to server

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#132]
I am trying to upload data on the server, but am stuck on the "please wait" screen.  I wonder if this is related to issue #126 

![screenshot_2017-04-16-21-08-34](https://cloud.githubusercontent.com/assets/9537700/25078559/f4d054ce-22e8-11e7-8f3b-7923f9f275c7.png)

**Comment by whppawan** [comment]
Yes it was.
It occurs when server internet goes slow down.

**Comment by space-ravi** [comment]
This issue is happening again today. I am unable to upload my data to the server.  Version 0.29 of the app on the playstore. If this is an issue with your server, then it needs to be fixed immediately.
