### ISSUE TITLE
"Other" in French and Swahili should behave like the English version

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#133]
When clicking "Other" option in English, a pop up comes up asking the user to enter the information. This should work the same for French "Autre" and Swahili "Mengine".

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Not working. Also, selecting "Other" in English doesn't work. See Prenatal Health Zone screen.

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
After pressing "Other", the popup comes, but then pressing OK the user returns to the same screen. The user should go to the next screen as indicated by the admin. 
http://103.225.41.0/ltfhcdynamic/admin/index.php?page=component&search_screen_id=35&start=&action=edit&id=189

Also, "Other" not working as expected on the subsequent "Prenatal Health Area 1" screen.

**Comment by whppawan** [comment]
Done
