### ISSUE TITLE
Missing report calculations

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#142]
I have not provided equations for 2 of the rows in the register. Please see the attached for those two equations. They are highlighted in yellow. 

[New Snis - rp - 2017-05-06.xlsx](https://github.com/kamal1978/LTFHC/files/981310/New.Snis.-.rp.-.2017-05-06.xlsx)

**Comment by kamal1978** [comment]
this is 1/2 done, team is working on it

**Comment by kamal1978** [comment]
hi Ravi, 

This is also done
