### ISSUE TITLE
Component ID 322 getting cut off

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#143]
I seem to have run into a character limit on ID 322. Is there a way to extend the limit so that the entire phrase will show? I need this text for the label: 
Est-ce que la patiente avait reçu la moustiquaire imprégnée d’insecticide à longue durée d’action (MILD)? 

Note that the last 4 characters are getting cut off. 

http://whpeportal.org/ltfhcdynamic/admin/index.php?page=component&search_screen_id=55&start=&action=edit&id=322

**Comment by whppawan** [comment]
Done
