### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#144]
I downloaded the latest apk (app-debug.apk), cleared the data, and then attempted to login using: 
username: test
pw: 123

When I press OK, I get a very quick "Please Wait" and then it goes away and I am still on the login screen. However, if I click "Choose Language" and then "English" as a language option, then I am taken to the Prenatal Main Menu screen.

**Comment by kamal1978** [comment]
We found the problem in logs, we will fix this today, 
Work around for this. 
Steps for new app installation
Install new apk
Before login click "Clear Data Button"
and then login

But this we will work, test and then upload to play store

**Comment by kamal1978** [comment]
Fixed

**Comment by kamal1978** [comment]
Hi Ravi, issue is fixed update on Playstore, it will take 2-3 hours for playstore to update the APK new version is 0.31
