### ISSUE TITLE
Issue using multiple accounts on tablet - crash on HCW name

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#147]
On a tablet, we have created multiple user accounts. One is an "administrator" that has access to everything. For the other users, we have limited access to just the ERCC app. If I create an account on the administrator account, and then switch over to the limited user account, there are several issues. One is: 
- After logging in, I press "Enter Patient Into Register". Then, on the next screen, after entering the HCW name and pressing OK, the app crashes. 

Note: I uploaded my data after this crash.

**Comment by whppawan** [comment]
Done
