### ISSUE TITLE
Report - Sulfadox calculations

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#152]
In the report, the Sulfadox calculations are not working correctly. Please see the attached spreadsheet for the calculations. This may be because the component option names were changed a while back.  

Also, please remove the '.' after the word Sulfadox on the report screen.
[Snis 2017-06-23.xlsx](https://github.com/kamal1978/LTFHC/files/1099201/Snis.2017-06-23.xlsx)

**Comment by whppawan** [comment]
Done
