### ISSUE TITLE
Register not updating after an edit

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#153]
I created a patient and left the entry for "Brachial Perimeter" blank. Then, I went to the register, clicked on the patient, clicked on Edit, and when I got to the "Brachial Perimeter" screen, I entered a value and pressed OK. Then, I pressed the back arrows until I returned to the main menu, and then clicked View Register.  The value in the cell for "Brachial Perimeter" was still blank.  

It's worth noting that if I click the patient's entry and go back to the "Brachial Perimeter" screen, the value I entered is still there. Also, the value was correctly calculated in the monthly report.

I am using v0.33 from the play store.

**Comment by whppawan** [comment]
We are looking the issue but not able to produce.

**Comment by space-ravi** [comment]
Reassigning to you while you investigate.
