### ISSUE TITLE
Report cutting off some data

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#157]
Version: playstore 0.34
Login credentials: th / 1234
Patient: Freddyy Flintstone

Issue: 
When entering the patient's information, I put that the patient has received tetanus vaccine 1,2,3; Fansidar 1,2,3,4; and Iron Folate 1,2,3+

When viewing the patient register, it seems like only the 1st of each of those shows up. All data should show up. 

See screenshots: 
Proof of data entered for patient: 
![screenshot_2017-07-25-20-39-40](https://user-images.githubusercontent.com/9537700/28603586-fc773398-7179-11e7-858e-ab19b2f5b409.png)

Register view of patient: 
![screenshot_2017-07-25-20-40-21](https://user-images.githubusercontent.com/9537700/28603595-05e99c90-717a-11e7-89c2-912ba962a654.png)

**Comment by kamal1978** [comment]
Hi Ravi,

I think it has been deliberately kept it is coded currently to show first selected option in the report. i think this has kept in this way to avoid mess up of report format. I have asked the team to add all the options, once done will send you screenshot of the report screen for you to decide.

**Comment by kamal1978** [comment]
This is done
