### ISSUE TITLE
Bluetooth sync not working

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#158]
Note from Jessica: 
_Bluetooth sync is not working. When I try to sync, I get the notification to accept the file but I can't click it, it disappears and when I go to notifications it just says "file not sent". Tried both sending from Tablet A to Tablet B and from Tablet B to Tablet A; didn't work either time._

Please test bluetooth sync and fix this issue ASAP.

**Comment by kamal1978** [comment]
This is not related to application, this is android feature, accept popup which comes is android bluetooth setting. I would suggest ask her to reboot the tablets and try again.

If problem persist try install this software 
https://play.google.com/store/apps/details?id=it.medieval.blueftp&hl=en

in some of the devices android default bluetooth system give problems.

**Comment by space-ravi** [comment]
Seems that restarting the app fixed one tablet, but another tablet is having issues. Any thoughts as to why? Here is Jessica's response:  
_Sync is now working after a restart. However, one of the tablets is still crashing when I try to upload the file-- same as before. Not sure why one is and the other isn't; they're on the same wifi and are running the same operating system and the same version of the app. I also hit "download" on both apps so they should be up to date. Restarted the problematic tablet and it still crashed when I tried to upload. Synced again to get a new file, and app crashed when I tried to upload that one as well._

**Comment by kamal1978** [comment]
I am little confused. 

Is this bluetooth sync or normal sync, as from jessica's response, it looks like there is problem in uploading data to the server not bluetooth sync. is it correct?

**Comment by space-ravi** [comment]
Ah, she was trying to bluetooth sync, but I wonder if she is not following the proper procedure. I'll check with her.

**Comment by space-ravi** [comment]
From Jessica: 
_There's no issue with bluetooth sync, that works fine. The problem is when I try to upload the shared file to the cloud-- that's when the app crashes (same as on the last version of the app)_

**Comment by kamal1978** [comment]
Hi Ravi 

Try to reinstall the application with clear data this is again permission issue which was reported by crashlytics.

**Comment by space-ravi** [comment]
Jessica is still experiencing this issue. She has tried: 
1. Press "Clear data" in the ERCC app
2. Delete the ERCC app
3. Restart the tablet
4. Reinstall the app
5. Accepted all permissions

and is still getting the issue. Please try to fix.

**Comment by space-ravi** [comment]
Jessica still having this issue. See my email.

**Comment by space-ravi** [comment]
Likely a tablet issue.
