### ISSUE TITLE
Trouble viewing the register

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#159]
Some of the tablets are having trouble viewing the register. Here is what they see: 
1. Date of visit: 0000-00-00
2. Time of visit: 00:00-00 
3. Boxes of Modifier and OK, Finished.
4. No patient information

Here is some additional information:
- Using the admin profile
- Username: jkongolo
- Version 0.35
- Language: French
- Uploaded data to server

**Comment by space-ravi** [comment]
It seems that clearing the data has resolved the problem. Please see if you find any issues, otherwise we can close this.

**Comment by kamal1978** [comment]
fixed
