### ISSUE TITLE
Some arrows are missing on screens

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#163]
We've had this issue several times. The LTFHC staff is reporting some screens have missing arrows (I'm not sure which screens). They cleared data on the old version, deleted the app, restarted the tablet, and installed version 1.0. Any thoughts on why forward/back arrows would be missing?

I personally don't see any missing arrows.

**Comment by whppawan** [comment]
We have tested in 3 tablets of different environment but not able to reproduce the issue.
Froward arrow is not shown in some of starting screen In which input fields are mandatory.
We will work more on it if you can tell the screen in which arrows are missing and different from those starting screens.

**Comment by space-ravi** [comment]
Issue resolved.
