### ISSUE TITLE
Reports should only show after data for month is received

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#170]
Updated comment below. Ignore this one. 

~~On admin website, the monthly reports should only show up after data from the entire month has been received. Otherwise, we risk incorrect reports being downloaded by individuals and organizations.~~ 

~~For example: If data from a clinic was last uploaded on Sept 15, on Oct 1, someone would see the report and think the report is complete. However, only if data has been uploaded after the end of the month should the report show up. That way, any report that gets downloaded is a complete and correct report.~~

**Comment by space-ravi** [comment]
Update: we decided that instead of showing up only after data received, it would contain a note if data from the end of the month had not been received. 

For example: If data were last uploaded on Sept 15, Sept reports would show up on the admin. However, until data through the end of Sept 30 is received, those reports should be marked with "Data last uploaded on September 15, 2017." in very clear visible writing. 

If easier, all reports can have the data last uploaded on date.

**Comment by kamal1978** [comment]
Hi Ravi,

It's done but I have not pushed it to production since everyone was on
holidays. I thought it would be better we will push it to production when
everyone is back.

Regards
Kamal

**Comment by space-ravi** [comment]
Great. And just to be clear, this should be for both admin webpage and tablet app.

**Comment by space-ravi** [comment]
If I go to a February report (or any report in Jan where data was not uploaded after the end of the month), then very clearly it should say "Data last uploaded on January 15, 2018". That way the viewer knows that the report is not complete.

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
The request was misunderstood. You put "Report uploaded till January 2018" on the main report page. This is something we need inside each report. Here is a use case. 

Today is Feb 13. If I am viewing a report from January for a specific health center, I need to know whether the report I am viewing contains all of January's data. The only way this is possible is if the health worker uploaded data in February. So if I click a specific report, that report should indicate when data was last uploaded. So a January report from health center A may have last uploaded data on Jan 25th. That report should say "Data last uploaded on Jan 25". A report from health center B may have last uploaded data on Feb 3. That report should say "Report complete". 

If this is difficult, we should discuss.

**Comment by whppawan** [comment]
Done
