### ISSUE TITLE
OK button not appearing on health care worker name screen

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#172]
On 6 tablets, the OK button does not appear on the "name of health care worker" screen.

OS ranges from 4.4.2, 4.4.4, 5.02.

**Comment by whppawan** [comment]
This can be handled by admin. Please reduce the left and right margin from 800 to 300 in button's attribute and take update in app.

**Comment by space-ravi** [comment]
Why would this show up on some tablets and not others?

**Comment by whppawan** [comment]
It is due to different resolution and configuration of tablets.

**Comment by space-ravi** [comment]
But they are all the same tablets (all Nexus 7).
