### ISSUE TITLE
Admin - Reports not viewable when logged in using French or Swahili

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#179]
In the admin, reports are only viewable when logged in using English. See attachments. 

<img width="1552" alt="admin in english" src="https://user-images.githubusercontent.com/9537700/33698116-4b8d2e7a-dabf-11e7-8c0b-df7f1db76476.png">

<img width="1552" alt="admin in french" src="https://user-images.githubusercontent.com/9537700/33698117-4ba0a2ca-dabf-11e7-9536-88f295f0651e.png">

**Comment by whppawan** [comment]
Done
