### ISSUE TITLE
Unresponsive entry in report list

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#181]
One report entry is unresponsive when I click on it in the report tab. The entry from Nyemba, M'toa. See 3rd row in screenshot. When I click on it, it does not go to the report. 

<img width="1552" alt="screen shot 2017-12-06 at 9 02 35 pm" src="https://user-images.githubusercontent.com/9537700/33699570-cc79391c-dac8-11e7-918b-6431a70ada8b.png">

**Comment by whppawan** [comment]
done
