### ISSUE TITLE
Admin translation request - pop up windows

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#184]
On the change password page, we need some translations added to the admin for the pop ups: 
- New password and confirm password are not matching
- Please fill current password
- Please fill new password
- Please enter at least 8 characters with uppercase letters, lowercase letters, and valid symbols
- Error: Entered current password is not matching with database

If I missed any pop ups please add those as well. 

I will ask LTFHC to provide translations.

**Comment by whppawan** [comment]
Done

5th phrase has been changed to "Your current password is incorrect" as it was mentioned in style sheet.

I have added one more phrase in style-sheet that was left to translate.
