### ISSUE TITLE
Admin translation missing

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#185]
A few more translations are missing from the [Report page](http://103.225.41.0/ltfhcdemo/admin/index.php?page=report&action=view) on the admin site.

First, Last, Next, and Previous are still in English.
Please see below the translations.

Swahili:
    First:  Mwanzo
    Next:  Ifuatayo 
    Previous: Iliopita
    Last:  Mwisho

French : 
    First:  Début
    Next:  Suivant
    Previous: Précédent
    Last:  Fin

**Comment by space-ravi** [comment]
Did we take away the first/next/etc navigation? Fine if we did but then I will close this. If they are still there, do I not see them because everything is on one page (and it will require more entries to split up into more pages)?

**Comment by whppawan** [comment]
Yes, due to small no of list we have remove this.
