### ISSUE TITLE
Issue viewing register

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#189]
When I log in as 
user: ekalwele
pw: kataki

and view the register, there is no option to view February, just Jan. I checked on the database (http://whpeportal.org/phpmyadmin/) and confirmed that there are patients in February. 

See attached picture. 
![screenshot_2018-02-10-11-39-42](https://user-images.githubusercontent.com/9537700/36066102-033100a2-0e59-11e8-904a-e2ecb98f7828.png)

**Comment by whppawan** [comment]
The attached screen seems of older version, because some content is in English and some is in French. Please let me know if the screen is of updated version. Because here we are getting the list.

**Comment by space-ravi** [comment]
This is v1.07. I am still getting this issue. I tried to upload the data from my tablet but when I do I get a message saying no data to synch (in French).

**Comment by space-ravi** [comment]
Seems fixed after I deleted ltfhcdynamic folder and reinstalled. I shouldn't have to do this so it's a little concerning. I'll go ahead and close out this issue and see if it happens again.
