### ISSUE TITLE
Missing arrows on all screens

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#191]
v1.07 of tablet. The health workers were not seeing the "Select Month" button on the register. I told them to upload data to server (I verified data was on server), then delete the ltfhcdynamic folder on the tablet. They did so. After that, the "Select Month" button appeared, but all arrows are now missing. See screenshots. 

![kataki 3](https://user-images.githubusercontent.com/9537700/36239293-216af1ec-11bd-11e8-8ea4-70aaf3a146d8.jpg)
![kataki 2](https://user-images.githubusercontent.com/9537700/36239294-21832078-11bd-11e8-94c6-e64c375404c8.jpg)

**Comment by space-ravi** [comment]
Same issue is happening on another tablet where the ltfhcdynamic folder was deleted and then data downloaded from server. I am also experiencing this issue.

**Comment by kamal1978** [comment]
Hi Ravi,

If the folder is deleted the user may need to reinstall to application as the images are stored in the ltfhcdynamic folder hence once the folder is deleted app does not locate the respective arrow images. 

it is downloaded one time at the time of installation of application, it is kept in such a way to avoid excess download bandwidth.

So if they re-install the application they will get the arrows. Before they uninstall and remove folder they should upload all the data to the server to avoid data loss.

Regards
Kamal

**Comment by space-ravi** [comment]
I tried this. I deleted the app, deleted the folder, reinstalled the app, and still no arrows. I also deleted the app again and reinstalled again just as another attempt.

**Comment by whppawan** [comment]
Please check now.
