### ISSUE TITLE
Register data not showing up

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#192]
I deleted the app and erased the ltfhcdynamic file from the tablet. I then downloaded the app (v1.07) and logged in as 
Username ekalwele 
Password kataki

When I go to the register, I don't see any data. The menu only gives Dec 2017 as an option. On the server there is data in Jan and Feb. 

![screenshot_2018-02-15-19-39-33](https://user-images.githubusercontent.com/9537700/36292685-6b342c3c-1288-11e8-87f8-5fdce3ad44ab.png)

**Comment by space-ravi** [comment]
Similarly: no data and no months for:
Username: cmulibinge
Password: mtoa

**Comment by kamal1978** [comment]
Hi Ravi

I am able to see all the data for this login. You may have to select french
language and download data , attached is the screenshot

Regards
Kamal

**Comment by space-ravi** [comment]
Argh of course. My fault, thanks for the reminder...
