### ISSUE TITLE
1970 year showing up on admin site

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#193]
Not sure why 1970 shows up in the year list. See attachment.

<img width="1428" alt="screen shot 2018-02-15 at 8 27 06 pm" src="https://user-images.githubusercontent.com/9537700/36293437-b8f9a176-128e-11e8-8d78-6286367a641a.png">

**Comment by kamal1978** [comment]
Hi Ravi,

This year is coming from one user cumlibinge, i think this is the new user and the date on the tablet is not set this is the case default mysql date is been sent to the database.

You may need to ask the user to set the date on the tablet and sync it.

Regards
Kamal

**Comment by space-ravi** [comment]
But when I click 1970 and then filter, no results show up. And no reports show a year of 1970. So isn't something wrong on the admin side?

**Comment by whppawan** [comment]
It may due to language restriction, but now its coming.
