### ISSUE TITLE
Reports in admin site not calculating properly

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#194]
On the tablet, if I log in as ekalwele (pw: kataki), I see many patients in February with CPN 1-4+ (French language). However, in the admin site, the Feb 2018 Kataki report shows all 0's. This means the admin report is not grabbing the appropriate data.

**Comment by space-ravi** [comment]
Kamal to check that register and report on tablet are showing for current logged in user only.

**Comment by whppawan** [comment]
Done
