### ISSUE TITLE
Not seeing all patients in tablet register

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#196]
Username: ekalwele
Pw: kataki
Version 1.07

When selecting the month in the Register, we did not see August, September and October 2017. I am able to replicate this issue that the field workers are experiencing. 

When I go to the server, I see patients with patient_id starting with ekalwele (e.g. ekalwele-215-20170922120127) in September. In that entry, tablet_entry_time is NULL. Is that related to the issue?

**Comment by whppawan** [comment]
tablet entry time was not related to the issue. There was some other issue which has been fixed.
Please Delete the folder and download data again.
