### ISSUE TITLE
Default sorting in admin site is unintuitive

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#197]
The default sorting in the admin site for the reports is unintuitive. Can we please sort to have the most recent reports on top? 

Ideally, could you do something like: 
1. First sort by Department (ascending)
2. Then sort by Health Area (ascending)
3. Then sort by Health Zone (ascending)
4. Then sort by month (descending by month, not alphabetical)
5. Then sort by year (descending)

I believe this will have the sorting such that the most recent reports are on top, and are also alphabetical by Health Zone/Area. 

If that is too complicated, please just sort to have the most recent reports on top.

**Comment by kamal1978** [comment]
This done based on Department -> User -> Year and then Month

**Comment by space-ravi** [comment]
My comment may have been confusing. The final output should be sorted by date (most recent on top) with the other fields alphabetical within that sorting. The result should look like the below (results are sorted by most recent on top, and user names are alphabetical within that sorting): 

Department | User | Year | Month
Prenatal   Department | bkasanga | 2018 | February
Prenatal   Department | cmulibinge | 2018 | February
Prenatal   Department | ekalwele | 2018 | February
Prenatal   Department | bkasanga | 2018 | January
Prenatal   Department | cmulibinge | 2018 | January
Prenatal   Department | ekalwele | 2018 | January
Prenatal   Department | jkongolo | 2018 | January
Prenatal   Department | mawazi | 2018 | January
Prenatal   Department | rprakash | 2018 | January
Prenatal   Department | asumaili | 2017 | December
Prenatal   Department | bkasanga | 2017 | December
Prenatal   Department | cmulibinge | 2017 | December
Prenatal   Department | ekalwele | 2017 | December
Prenatal   Department | jkongolo | 2017 | December
Prenatal   Department | rprakash | 2017 | December
Prenatal   Department | test | 2017 | December
Prenatal   Department | amutiki | 2017 | November
Prenatal   Department | asumaili | 2017 | November
Prenatal   Department | bkasanga | 2017 | November
Prenatal   Department | cmulibinge | 2017 | November
Prenatal   Department | ekalwele | 2017 | November
Prenatal   Department | jkongolo | 2017 | November
Prenatal   Department | mawazi | 2017 | November
Prenatal   Department | nwallon | 2017 | November
Prenatal   Department | pningila | 2017 | November
Prenatal   Department | rprakash | 2017 | November
Prenatal   Department | bkasanga | 2017 | October
Prenatal   Department | ekalwele | 2017 | October
Prenatal   Department | jkongolo | 2017 | October
Prenatal   Department | nwallon | 2017 | October
Prenatal   Department | rprakash | 2017 | October
Prenatal   Department | test | 2017 | October
Prenatal   Department | bkasanga | 2017 | September
Prenatal   Department | ekalwele | 2017 | September
Prenatal   Department | nwallon | 2017 | September
Prenatal   Department | rprakash | 2017 | September
Prenatal   Department | amutiki | 2017 | August
Prenatal   Department | bkasanga | 2017 | August
Prenatal   Department | ekalwele | 2017 | August
Prenatal   Department | mkosani | 2017 | August
Prenatal   Department | nwallon | 2017 | August
Prenatal   Department | rprakash | 2017 | August
Prenatal   Department | vmulila | 2017 | August
Prenatal   Department | cmulibinge | 1970 | January

**Comment by whppawan** [comment]
Done
