### ISSUE TITLE
Potential error in report "year" entry

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#198]
In admin, there is a report from Kataki that has a year of -0001. Is this user cumlibinge? Or is this an error with the admin site? See attachment 3rd row from bottom. 

<img width="1552" alt="screen shot 2018-02-16 at 12 36 07 pm" src="https://user-images.githubusercontent.com/9537700/36328206-27200334-1316-11e8-8f5b-f4d1d4158d6f.png">

**Comment by space-ravi** [comment]
user asumaili and cumlibinge - last error on 14 Dec. Tablet entry time is not proper.  Beaconpath to make tablet entry time same as patient entry time.

**Comment by whppawan** [comment]
Fixed
