### ISSUE TITLE
Questions about admin

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#199]
A couple questions about the admin reports. I just want to confirm the way it works. 
1. Are the "Health Zone" and "Health Area" columns from the health worker's profile (or the patient's profiles?)
2. Let's say 2 health workers are sharing a tablet but have different login names. They have separate reports? (As opposed to a combined report?).

**Comment by space-ravi** [comment]
Answers: 
1. Right now on admin these fields are based on patient's profiles. Should be health workers profiles. Steps: 
a) remove Health Zone and Health Area fields on admin (Beaconpath)
b) Add user filter to admin (Beaconpath)
c) Ravi will provide list of drop down for tablet for HZ and HA fields
d) Clean up the server side (Ravi can do if he has server privileges)
e) Beaconpath can update admin to reflect HZ and HA options

**Comment by whppawan** [comment]
a and b has been done

**Comment by space-ravi** [comment]
c) is below. Note that we will occasionally update this list with additional health zones and health areas. I will need to chat with Pawan to do part d).

Health Zones: 
- Kalemie
- Nyemba

Health Areas (please alphabetize): 
- Katondo
- Tembwe
- Kimena
- Katibili
- Kataki
- Undungu
- Mtoa
- Kitoke
- Rugumba
- Wimbi

**Comment by kamal1978** [comment]
if you want this configurable from admin panel, we have to built that feature that would be an enhancement and also have to define APIs to sync with mobile app. It is doable for sure, this would be an added workflow and will be taken as enhancements

**Comment by space-ravi** [comment]
How about instead of configurable from admin you hard code it and if we need to make adjustments you can add an additional health area or health zone? I assume that is much easier and also will take negligible time for additions?

**Comment by kamal1978** [comment]
We can do the hard coding of it, but everytime you change any health zone or health area we will need to update back date data and also if you add any HA or HZ , we will have to sent out a mobile app release. Which is seems not feasible, can we have a quick call tomorrow or today to discuss this

**Comment by space-ravi** [comment]
Ah ok. How about we discuss at 9 am your time tomorrow?

**Comment by kamal1978** [comment]
Hi Ravi,

 

I have another call at 8:30 am tomorrow, if you are ok I can do it tonight say 9:30 india time or else tomorrow 9:30 am

 

Regards

Kamal

**Comment by space-ravi** [comment]
Let's do 930 AM on Wed 2/21. Thanks!

**Comment by space-ravi** [comment]
Will close this out and create new ticket with enhancement discussed on Skype chat.
