### ISSUE TITLE
Make health worker details configurable in admin

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#200]
At account creation, the health workers currently enter (freeform text) a Health Zone and Health Area. This should be a dropdown list that is configurable in the admin. (as discussed on Skype call on 2018-02-20). This way, LTFHC can enter the possible Health Zones and Health Areas (and modify that list over time).

**Comment by whppawan** [comment]
Controls to enter Health Zone and Health Area are made in admin.
Integration in app is pending.
