### ISSUE TITLE
Only download a specific user's data to tablet

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#206]
To decrease register loading time, the tablets should only download the current user's data. Let's talk about this before you implement. I believe this means: 
- We should take away the "upload/download" menu on the login page (can keep the share data option). First time app is open, it will download screens, credentials, etc. 
- We should keep the upload/download menu after log in
- The user will have to press "download data" for the data to be downloaded from the server
- To get rid of other HCWs data on each tablet: Upload data, then delete files on tablet, then re log in and download data just for logged in health worker

Scenarios: 
- User 1 creates account on new tablet. After creating account, user 1 has data that is stored locally on the tablet. Once the user uploads data to server, the data is on the cloud ready for him to retrieve. 

- User 2 has an existing account and logs onto User 1's tablet. Then presses download. Both user 1 and user 2 data exist on tablet.

**Comment by space-ravi** [comment]
I'm not sure this was done correctly. I deleted the app and deleted the ltfhcdynamic folder on the tablet. I downloaded the APK file. Then, I turned off WiFi, and was able to login as 3 different users. I would have expected to not be able to log in as any user since the tablet should not have known any credentials.

**Comment by space-ravi** [comment]
Still not working. I deleted the app and ltfhcdynamic file and downloaded the apk file. I then do the following checks: 

- Log in as rprakash, logs in (as expected)
- Turn off WiFi, log in as rprakash, logs in (as expected)
- With WiFi still off, I log in as bkasanga - should NOT log in, but does

In addition, when I first entered my credentials (for user rprakash) and press OK, a spinning wheel turns for a long time and then after a while, the screen does not advance past the login screen (but the spinning wheel goes away). After pressing "OK" again, the screen advances to the main menu (instantly).

**Comment by whppawan** [comment]
Only patient data can be downloaded by clicking on download button. Anyone can login offline in app whose account has been created and synced to server. because hcw users' data pushed to app on start as it's size is very low. But patient will be shown only after downloading from server by hitting download button.
