### ISSUE TITLE
Translation fixes - app

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#210]
On the tablet app, please update the following in FRENCH (I don't have access to these items):

We want in French the OK button should be OK (not D'accord). This shows up on the following screens: 
Login screen: Change D'accord to OK
On "View Report", the select month option should say OK (not D'accord)
 
Also, on the register screen, please change "Main Principal"  into  "Menu Principal"

**Comment by whppawan** [comment]
Translation of D'accord to OK has been done.

For second point that should come from admin but only in french case it's not taking effect. For English and  Swahili it works fine. We are looking into it.

**Comment by space-ravi** [comment]
Thanks, I assume we'll need a playstore update to see the changes?

For Menu Principal, it wasn't changing because the component attribute had value: "Main Principal". I changed it so it's working now.

**Comment by space-ravi** [comment]
Waiting on Android dev for View Report button. Then will likely need playstore update.

**Comment by whppawan** [comment]
For view report, we do not need playstore update because it is comming from admin. It's a button so it's will not change by changing the. It needs to be changed valued mentioned in attribute column.

Please change value in component attribute tab.

**Comment by space-ravi** [comment]
I am referring to the Select Month screen when the user clicks "View Report". I don't believe this is something I can edit. 

See attached. "D'accord" should say "OK"
![screenshot_2018-04-06-20-56-17](https://user-images.githubusercontent.com/9537700/38451032-313a62d6-39dd-11e8-82ba-67f4e8ed56dc.png)
