### ISSUE TITLE
Translation fixes - admin site

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#211]
Please make the following translation updates on the admin site (Report tab) - FRENCH language: 
- While "select month" dropdown has months in French, the actual months in the table are in English. Please also make these in French.
- "Select User" in French is not linked in Language tab of admin. Should be: "Sélectionner l'utilisateur"

**Comment by whppawan** [comment]
First part done. Working on second one.

**Comment by space-ravi** [comment]
The first part still has English words for the months in the month column. 
<img width="1393" alt="screen shot 2018-03-22 at 8 05 02 am" src="https://user-images.githubusercontent.com/9537700/37778667-bf9415a0-2da7-11e8-9bcd-275b92e10c43.png">

**Comment by whppawan** [comment]
Done
