### ISSUE TITLE
Report calculation update

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#212]
On the report (admin and app), this calculation should be updated: 

Mosquito-net MILD distributed during CPN 2+
IF(ID344 == YES) AND (ID237 = 2nd, or ID237 = 3rd, or ID237 = 4+), then ++

Basically if the user received a mosquito net on their 2nd, 3rd, or 4+ visit, we want this to increment.

**Comment by whppawan** [comment]
Done

**Comment by whppawan** [comment]
Pending in app

**Comment by space-ravi** [comment]
Reassigning until complete in app
