### ISSUE TITLE
Report last uploaded date is incorrect

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#214]
Related to issue #170 that we previously closed out. 

On admin site, each report should either say "Report complete" or  "Report uploaded till (some date)"
1. The report should say "Report complete" only if data has been uploaded **after** the end of the month for that report. 
2. The report should say "Report uploaded till (some date)" for reports where the last upload was in that current month. 

I see an issue with the following reports (there are probably others, I just spot checked): 
User: test
Report: December 2017
That report says "Report uploaded till 16-Mar-2018". However, if data was uploaded on that date, then the report should be complete (since 2018-Mar-16 is after Dec 2017).

In addition, for user bkasanga, on the server, it looks like the last upload was on 2018-02-07, but the Feb 2018 report shows as "Report complete" for this user.

**Comment by space-ravi** [comment]
Still seeing issues. See attached which is a Dec 2017 report, but comment says that report is uploaded until 27-March-2018. 

<img width="1530" alt="screen shot 2018-04-07 at 3 21 30 pm" src="https://user-images.githubusercontent.com/9537700/38460857-72962f90-3a77-11e8-9f93-9aa36026b329.png">

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
We need to talk about this one again. I don't think we are on the same page with what is needed. It looks like all the algorithm is doing is saying if the report month is in the past, say it is complete. This is wrong. 

For example, the report from Kalemie/Kataki for March 2018 says Report Complete (user ekalwele). However, this user's last entry time was March 16, 2018, so how can that report be complete?

The algorithm is simple: 
- For a given user, save the last upload date
- All months prior to that date should have report complete
- The month of the last upload date should have "Report uploaded till [date]"

**Comment by space-ravi** [comment]
I am not sure that the reports are posting properly. On the database I see data entered for September, but the prod server reports tab does not have any partial reports from Sept.
