### ISSUE TITLE
Component not syncing to report

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#215]
Component ID 608 (Man HIV Code on screen "Prenatal Man HIV Code") is not syncing to the report (when data is entered into that field, it does not show up in the report). I can't find the place in the admin where I put all the component IDs in the order they should go in the report (I thought it was Village Analysis Report but the component options there just show "patient given name" over and over. Am I looking in the right place?). Please either remedy or let me know how to modify.  

![screen shot 2018-03-27 at 8 06 03 pm](https://user-images.githubusercontent.com/9537700/38006554-5c64e2b4-31fa-11e8-9b54-a3e7a5a72c5a.png)

**Comment by whppawan** [comment]
It's "Patient Registration Report".
