### ISSUE TITLE
New HCW location in database

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#217]
I created a new user in the app (username uhyg). 
In the database, the hcw_zone and hcw_area show up as numbers now instead of text. 
I am assuming this is not expected behavior.

**Comment by whppawan** [comment]
The field hcw_zone and hcw_area have no more use in the application and will be removed once related issues resolved.

**Comment by space-ravi** [comment]
I'm not sure I understand this. Why are these fields no longer needed? We are recording the health worker's health zone and health area, and we need to store these values in the database.

**Comment by whppawan** [comment]
We have created two new field hcw_zone_id and hcw_area_id to store the information about hcw_zone and hcw_area which are connected with respective masters.
