### ISSUE TITLE
Icons missing (again)

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#218]
I am using version 1.09. All my icons have disappeared (arrows, home buttons). However, if I press where they should be, the functionality works. 

We've had this problem numerous times and I thought you did something to where you said the problem would not happen again. How can we fix this permanently?

**Comment by whppawan** [comment]
Done.

Process:
1. Delete the "ltfhcdynamic" folder from tablet.
2. Clear data from setting.
3. Uninstall ercc app.
4. Install the APK version 1.10 which i have shared on mail.

Now open the app and check.

**Comment by space-ravi** [comment]
Working now. Did you fix a bug or does the process you describe just fix the problem? If it's the latter, then I feel like this will keep happening.

**Comment by whppawan** [comment]
This process need to be done each time when the ltfhcdynamic folder deleted in tablet.

**Comment by space-ravi** [comment]
I'm asking a different question: Did you fix a bug related to this problem? 

If you did not fix a bug, then I think this problem will keep happening.

**Comment by whppawan** [comment]
Yes, I have fixed the bug.
