### ISSUE TITLE
Add Screen verbiage changes

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#22]
On the [Add Screen](http://103.225.41.0/ltfhcdynamic/admin/index.php?page=screen&action=add) page, please change the following verbiage: 

- "Screen Name": Change to "Screen Title"
- "Enter Screen Name": Change to "Enter Screen Name"

**Comment by whppawan** [comment]
"Screen Name" has not been needed to change as "Screen Title" because it is not being used as screen title. Screen title is also a component of 'label' type.
I think the second is mentioned by mistake.

**Comment by space-ravi** [comment]
Thanks @whppawan ...how is screen name being used?  Just to have a way to reference the slide for the layout and component sections?

**Comment by whppawan** [comment]
Yes

**Comment by space-ravi** [comment]
Ok, then no action to take here.
