### ISSUE TITLE
Users unable to upload data

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#223]
Users are unable to upload data. See error message below when attempting to upload data. The same issue exists for the following users:
abahati
gngoy
cfatiya
smamba

![upload_message 1](https://user-images.githubusercontent.com/9537700/38845692-8ab301ec-41ad-11e8-8230-da949999ea4c.jpg)

**Comment by space-ravi** [comment]
Maybe this is related to not having the login credentials uploaded to the server (??)

**Comment by whppawan** [comment]
Done.
