### ISSUE TITLE
Issue logging into tablet

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#224]
Same issue I discussed on phone last week is happening: 
- When I log into app, I type in username and pw
- I get the spinning wheel forever
- I quit app
- I relaunch app
- I am automatically logged in

**Comment by whppawan** [comment]
Is prompt to allow storage is coming in new app? If yes then it needs to be allowed.
Please check and let me know if the prompt not coming.

**Comment by space-ravi** [comment]
Prompt is not coming

**Comment by space-ravi** [comment]
Kamal suggests upgrading to 5.1.1 and see if this fixes the problem.

**Comment by space-ravi** [comment]
With v1.10 from playstore on OS 4.2.2 no issues.
