### ISSUE TITLE
Don't see "Select Month" on register

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#225]
User: rprakash, version 1.10
My register is empty and I don't see "Select Month" on the register. See screenshot: 
![screenshot_2018-04-23-20-12-22](https://user-images.githubusercontent.com/9537700/39164197-06e0332c-4733-11e8-941e-9ee2bd635cd8.png)

**Comment by whppawan** [comment]
The demo app is linked with" http://103.225.41.0/ltfhcdemo" URL and there month dropdown was not created in admin. Now I have created it there. please check now.
