### ISSUE TITLE
Forgot Password issues

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#227]
Two issues with the forgot password feature:
1. The link in the email is not a hyperlink (you cannot click it, you have to copy/paste).  I sent Pawan an example. 

2. When I attempted to change my password, a special character doesn't seem to work: "#"
For example, I tried to change my password to: Password#123 and that did not work, even though it lists "#" as an option for a special character.

**Comment by whppawan** [comment]
2nd point is resolved.
