### ISSUE TITLE
Change password issue

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#228]
After reseting my password via the forgot password link, I tried to change my password. It does not recognize my password. See screenshot. 

![screen shot 2018-05-11 at 6 56 02 am](https://user-images.githubusercontent.com/9537700/39927890-8b34a776-54e8-11e8-94ce-38db48ad12e5.png)

**Comment by whppawan** [comment]
We are not able to produce this issue. The error is only coming at the time of mismatch of current password. Please try again and make sure that there must not any space before or after the current password you have entered.

**Comment by space-ravi** [comment]
I'm still having the issue. Try logging in as me (un: raviprakash02@gmail.com, pw: Password@123). I then am changing my password to one autogenerated by my password generation tool: 6K$7Kfi8#2Mj!gvv

**Comment by whppawan** [comment]
Please check now.
