### ISSUE TITLE
Component ID should be on Add Component screen

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#23]
On [Add Component](http://103.225.41.0/ltfhcdynamic/admin/index.php?page=component&action=add) page, please add in Component ID above the Component Name. It should be prefilled out with the component ID number for the particular component. 

If this is difficult, let's chat.

**Comment by whppawan** [comment]
Component id can be shown when the component is being edited. What about the new component that has to be added? Do I need to show the projected ID of that component or leave the field blank with read only?

**Comment by space-ravi** [comment]
It would be good to show the projected ID if that is possible.

**Comment by whppawan** [comment]
Done
