### ISSUE TITLE
Admin: get rid of home screen

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#232]
After logging in on the admin site, the user lands on the "Home" tab. Please get rid of the Home tab since there is no value there. After logging in, go straight to the Report tab.

**Comment by whppawan** [comment]
Done.

Should the home page and tab be removed or it should be remain as it is?

**Comment by space-ravi** [comment]
Thanks Pawan, please get rid of Home page.

**Comment by whppawan** [comment]
Done
