### ISSUE TITLE
Admin reports not exporting - French language

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#233]
In the admin site, French language, the reports are not exporting into csv, Excel, or pdf (works fine in English and Swahili).

**Comment by whppawan** [comment]
This occurs due to special characters used in french language. I have changed "DÃ©partement PrÃ©natal" to "Prenatal Department" to make it working.
Also working on permanent solution of this issue.

**Comment by space-ravi** [comment]
Thanks, please let me know the status of finding a permanent fix.

**Comment by whppawan** [comment]
Fixed in demo URL
