### ISSUE TITLE
Report calculation change

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#234]
The prenatal register was asking for "Pb in cm". Turns out we should be asking for "Pb in mm". Therefore, the calculation in the report for "Pregnant women with Pb < 230 mm" needs to be adjusted. The current calculation is if ID214 < 23, then add to the value in the report. However, it should be if "ID214 < 230" then add to the value in the report.

Please make sure to change in all languages. Also please make sure the admin report on the web will also reflect this change.

**Comment by whppawan** [comment]
It will give wrong result for earlier records which has been entered in "cm". If it is OK then let me know, i will  change the calculation.

**Comment by whppawan** [comment]
Done in Demo URL

**Comment by space-ravi** [comment]
In demo apk I have added 2 patients. One with Pb = 25, 1 with Pb = 231. When I go to the report for August 2018, I don't see any patients with Pb < 230 mm. I should see 1 patient.

**Comment by whppawan** [comment]
Earlier it was not implemented in APK. Its done now. Please check the new APK I have mailed you.
