### ISSUE TITLE
Prod changes on admin not updating to tablet

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#235]
Related to #234 
On the admin prod site, for component "Prenatal Brachial Perimeter" I changed the question to ask in mm. However, on my device, after pressing "download", I still see the question being asked in cm.

**Comment by whppawan** [comment]
Make sure that you are using the play store play store app not the one which I mailed you testing. Because testing app routes testing server and the changes are done in prod.
Because I can see 'mm' instead of 'cm' for the particular question in my side.
