### ISSUE TITLE
Trouble creating new screens on admin

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#236]
This is on demo admin site. 

I have created a new screen: "All Register Menu" and new layouts for that screen. When I try to create a new component, I keep getting this error, even though I am copy/pasting exactly from an existing screen. I am trying to replicate the "Prenatal Main Menu" for the next register.

Furthermore, when I try to save an existing screen, I get the same error. 

<img width="1552" alt="screen shot 2018-08-05 at 5 35 41 pm" src="https://user-images.githubusercontent.com/9537700/43691832-a8e020e8-98d6-11e8-9221-528311334b39.png">

**Comment by whppawan** [comment]
Done
