### ISSUE TITLE
App screen after login is odd

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#237]
I downloaded the APK delivered on Aug 6 and after logging in, I get this screen (blank). I cleared the data, deleted the app, reinstalled the APK, and keep getting the same screen. I then cleared the data, deleted the app, and installed the play store app and get the same screen. I also tried restarting the tablet and get the same result. 

![screenshot_2018-08-06-20-33-57](https://user-images.githubusercontent.com/9537700/43753015-832ef45e-99b8-11e8-9542-7a5728cf3ec3.png)

**Comment by whppawan** [comment]
Currently you are clearing the data before deleting the app. Just for confirming the issue what we are thinking try once more by clearing the data after installing the app then open it and let me know if still getting blank screen.

**Comment by space-ravi** [comment]
Issue still persists after trying the above
