### ISSUE TITLE
Dev APK file crashing with any button press

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#238]
I am working on the APK file delivered on (v 1.13). I deleted the app, cleared the memory, and deleted the ltfhcdynamic folder. 

When I log into the app, on the main menu, I click on "Enter patient into register". The app crashes. If I change the starting screen to any other screen, the app crashes whenever I press any button. 

I need the dev APK working to test out the new screens I am making on that site. 

In case it helps, the Prenatal Main Menu screen is the first screen in the sequence (same as in prod). So the issue is not related to any of the screens I have created for the CPS register.

**Comment by whppawan** [comment]
The issue is tackleed. It's due to the size of file generating in the device. We are working on it and will let you know as soon as it rectified.

**Comment by space-ravi** [comment]
Is this resolved? Please only assign to me when the issue is completely resolved.
