### ISSUE TITLE
Unable to load images to admin

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#240]
It seems I am unable to load images to the admin. For example, component ID 714 (Screen: CPS HCW Name, Component name: home) I loaded the attached image (note image is white so you may not be able to see it in this comment, but you can click it). In the admin, the image does not appear. When I view the screen in the tablet, there is no image there. This same issue is happening on all screens where I am added home icons, backward arrows, and forward arrows. Issue persists if I delete the ltfhcdynamic folder and app from the tablet and reinstall. 

![ic_home](https://user-images.githubusercontent.com/9537700/45592739-7fe0bd00-b92a-11e8-8fba-facfdbefe82c.png)

![screen shot 2018-09-15 at 9 01 29 pm](https://user-images.githubusercontent.com/9537700/45592746-88d18e80-b92a-11e8-9db1-c7b82746b475.png)

**Comment by whppawan** [comment]
Done

**Comment by whppawan** [comment]
I have uploaded the home image on component you have attached here. You have to upload the images in all other components too.

**Comment by space-ravi** [comment]
Was there an issue that was fixed? Or did you just upload the image for me?

**Comment by whppawan** [comment]
It was permission issue on server.
