### ISSUE TITLE
Help with Main Menu creation on admin

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#242]
On the dev admin, please see the screen called "All Register Menu". 

I am trying to make this screen a dropdown of all the registers (right now the options are: CPN, CPS, CPS Vaccine). Then, depending on the option the user selects, the proper register screen will come up. 

Can you help me create this main menu screen? I am having trouble. We can talk about this over the phone if that's easier.

**Comment by whppawan** [comment]
Routing different screen depending upon the drop-down value is not possible in this app. For routing different screen you have to make different components.
You can route the screen by setting "onclick" event in "component form" at admin which works for whole component not for individual value.

**Comment by space-ravi** [comment]
Note to self: Going to need to find a solution for this when more registers are added.

**Comment by space-ravi** [comment]
Logic adding abilities takes care of this.
