### ISSUE TITLE
Issue changing screen in admin

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#245]
I am modifying a screen in the admin (Component ID 835, Screen: CPS Vaccination BCG, Layout: Subheader, Component: No_BCG).

I am trying to change the component options and the also on click I do not want to save. When I erase the component options and then press "Submit", the values return. When I change Save to "Select Function", the "Save" value returns. 

Same issue happens for component 837.

**Comment by whppawan** [comment]
Resolved
