### ISSUE TITLE
Issues creating two buttons on screen

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#247]
On screen: "CPS Vaccination BCG", layout "Buttons", I am having trouble creating two buttons (as separate components) side by side. Can you please let me know what I am doing wrong? 1 button is "OK" and the other button is "No BCG". 

Shortcut to test out the screen is to go to "CPS Vaccination" from the main menu, click on "View Register" and the next screen is the BCG screen.

**Comment by whppawan** [comment]
You were doing right. There was a bug in admin which did not allow to save empty value. Due to this you may have given space in "component option" to make it empty. Due to this the button was unable to incorporate the defined attributes.
Now it is fixed.
