### ISSUE TITLE
Dates are not showing up in patient summary or in register

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#249]
None of the dates that I am saving are showing up in the patient summary or the register. For example:
Screen: CPS Vaccination DOB
Component ID: 829 (DOB (DD/MM/YY))
This component is marked as save value. 

When I go through the app and enter a value for this item, the DOB does not show up in the patient summary or in the register.

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Works for DOB field but not for others (e.g. BCG screen, VPO 0, etc). This is in the CPS Vaccination register.

**Comment by whppawan** [comment]
Done
