### ISSUE TITLE
Report for CPS and CPS Vaccine

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#250]
CPS Report (screen and layouts already exist in admin): 
- Report should look like attached tab "CPS Report section 8.1 and 8.2"
- English headings are in Col B (english report should not contain Col C)
- French headings are in Col C (french report should not contain Col B)
- Equations are in the cells. 

CPS Vaccine Report (screen and layouts already exist in admin): 
- Report should look like attached tab "CPS Report section 8.3 and 8.4"
- English headings are in Col B (english report should not contain Col C)
- French headings are in Col C (french report should not contain Col B)
- Equations are in the cells. 
- Note that 8.3 will be empty. 

[CPS.Registers.vs.report.SNIS.English.-.rp.2018-11-17.Beaconpath.xlsx](https://github.com/kamal1978/LTFHC/files/2592532/CPS.Registers.vs.report.SNIS.English.-.rp.2018-11-17.Beaconpath.xlsx)

**Comment by space-ravi** [comment]
Reports are not calculating correctly. Some examples of issues from the CPS Vaccination report for user rprakash (pw 1234): 

- I put a user as born on 18-Jan-2018 (so she should be 12 months old). This patient (Tasha Prakash) had a BCG vaccine on 18-Jan-2019 (Fixe). When I view the Jan 2019 report, I should see a "1" next to BCG Fixe for 12-24 months old. But it remains 0. 
- I have entered 2 patients, both female. When I go to the report, there is a 2 in the female column for BCG (correct), but also 2 for male (incorrect). 
- The report shows 2 males and females have received all the vaccines (incorrect)

**Comment by space-ravi** [comment]
Updated report spreadsheet attached. Changes are highlighted. 
1st tab (8.1, 8.2): Row 15 has updated equations
2nd tab (8.3, 8.4): I realized I was using age from the CPS register instead of the CPS Vaccine register. The problem is, in the CPS Vaccine register, we are asking for DOB, not age. Some options here to discuss: 

Option 1: We calculate age (in months) based on DOB and time that the patient was entered into the tablet
Option 2: I ask LTFHC if it is ok to ask for age in months instead of DOB

Do you have thoughts on this?

**Comment by space-ravi** [comment]
[CPS.Registers.vs.report.SNIS.English.-.rp.2019-01-23.Beaconpath.xlsx](https://github.com/kamal1978/LTFHC/files/2829777/CPS.Registers.vs.report.SNIS.English.-.rp.2019-01-23.Beaconpath.xlsx)

**Comment by space-ravi** [comment]
Ravi to check if this has been fixed.

**Comment by space-ravi** [comment]
User: rprakash, version: "LTFHC 19th Sep.apk", data uploaded to server

There are still issues in the CPS Vaccine report: 
- See screenshots. 
- BCG row shows 1 in the total column, but no numbers in the previous columns (based on my input, there should be a "1" in the fixed column for 0-11 months (1st screenshot), and a 1 in the fixed column for 12-23 months (3rd screenshot).
- See ECV row. The total column is not adding correctly.  (2nd, 4th screenshots)
- Female patients not showing up in 1st 6 columns (just in total) (3rd, 4th screenshots)
- Female patients add up as both female and male patients. (3rd, 4th screenshots)

![Screen1](https://user-images.githubusercontent.com/9537700/65822886-92115e80-e200-11e9-8f7f-d840c3c4f372.png)
![Screen2](https://user-images.githubusercontent.com/9537700/65822887-92a9f500-e200-11e9-9857-dd0e6a6cbb3f.png)

![Screen3](https://user-images.githubusercontent.com/9537700/65822967-20d2ab00-e202-11e9-9c72-71f8a2f2e7c0.png)

![Screen4](https://user-images.githubusercontent.com/9537700/65822968-23cd9b80-e202-11e9-9ab0-7661fc2836e5.png)

**Comment by whpVishal** [comment]
@space-ravi  i changed the queries for calculation of data, but in User: rprakash the patient list is showing empty. would like to know on which server and on which month selection i can test it.

**Comment by space-ravi** [comment]
I have re-uploaded the data in case there was an issue last time. It is user: rprakash and server is demo server: http://103.225.41.0/ltfhcdemo/admin/index.php
You can view the data under September 2019.

**Comment by space-ravi** [comment]
In case there is an issue with being able to upload data (see issue #273), then I encourage you to add patients to the register yourself (male and female) and you will notice the issues above.

**Comment by whpVishal** [comment]
changes has been made and new build is shared please test on the new build.

**Comment by space-ravi** [comment]
Using "LTFHC 10th Oct.apk", ALL of the same problems as before still exist. Please test thoroughly.

**Comment by whpVishal** [comment]
@space-ravi I think there is data missing for component_id '1010' which is for BCG. i tested it on October 2019. 
please have a look on this too and let me know

**Comment by space-ravi** [comment]
I saw a mistake in my component options for BCG (component_id 1010). I updated it, which should match the equation I gave you. However, the reporting is still not working for BCG.

**Comment by space-ravi** [comment]
Ravi found mistake that I made. Reassigning to me and then will check.
