### ISSUE TITLE
Date not saving when going back

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#251]
Perhaps related to #249, when I press "backward" on a screen to go back to a screen that has a date on it, the date that I entered previously is no longer there. Like the other fields, it should remain when returning to the screen.

**Comment by whppawan** [comment]
Resolved

**Comment by space-ravi** [comment]
Works for DOB field but not for others (e.g. BCG screen, VPO 0, etc). This is in the CPS Vaccination register.

**Comment by whppawan** [comment]
Resolved
