### ISSUE TITLE
CPS Vaccination report issues

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#257]
The CPS Vaccination report seems to have several issues: 
- Entered a patient age 7 months, but the entries were populated as if the patient was 12-23 months
- Entered 2 patients in register, but some rows in report show up as if there are 3 patients
- If I go to an older months report (which should show all 0's because there is no data for those months), I get the same report as the Feb report which has data.

**Comment by whppawan** [comment]
Done
