### ISSUE TITLE
Issue with report

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#258]
User has empty register, but report shows up with all data entered in Feb. 

username is: ekalwele and the password is kataki
Data is uploaded to server. 

![Febr register Kataki HC](https://user-images.githubusercontent.com/9537700/55176400-4c36e900-513e-11e9-9554-e88e6f17639b.jpg)

**Comment by sankus2212** [comment]
![Capture2](https://user-images.githubusercontent.com/43634164/55226373-dcf2ef00-523a-11e9-9a97-eb14218be015.PNG)
![Capture3](https://user-images.githubusercontent.com/43634164/55226374-dd8b8580-523a-11e9-9753-1e7cf6042c7a.PNG)
Reports and register both showing data.
