### ISSUE TITLE
OBGYN Report

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#263]
Please see attached for the OBGYN report. Let me know if you have any questions. I am hoping this can be implemented by June 25. 

Note that the left tables are for English language. The right tables are for French and Swahili (same tables for both). 

Reminder that the report should be implemented for both app and admin website. 

[OBGYN Report.pdf](https://github.com/kamal1978/LTFHC/files/3250491/OBGYN.Report.pdf)

**Comment by space-ravi** [comment]
Issues with Report: 
- Header row currently says "10. GYNECO OBSTECTRIC 10.1 Abortions"
-- Please have it only say "10. GYNECO OBSTECTRIC" 
-- Next row should say "10.1 Abortions"
-- Please remove row that says "Value(Eng)"

- Section 10.3 has several repeat rows (see screenshot) - Uterine rupture appears 3 times, Eclampsia appears twice. 

- Section 10.3 is missing the last row in the pdf (postpartum infection). 

![Screenshot_2019-10-11-08-46-59](https://user-images.githubusercontent.com/9537700/66665875-49947080-ec04-11e9-8bae-6d37cc056ffa.png)

**Comment by whpVishal** [comment]
@space-ravi  issue is resolved in today's build
