### ISSUE TITLE
Put register on admin website for Prenatal department

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#264]
Please start putting the Prenatal department register on the admin website. Only do this one for now so we can make sure it's what everyone is expecting. Would be ideal to be complete by June 25.

**Comment by space-ravi** [comment]
Filters still need to be fixed.

**Comment by kamal1978** [comment]
Hi Ravi, this is done, please check on demo site

**Comment by space-ravi** [comment]
Looks good. Some issues I noticed:
- Once a Health Zone is selected, "Select Health Area" just says "Select"
- "Select year" does not automatically show (some reason it is blank by default). Note that "Report" tab has same issue (but only on demo site, not on prod).
- After pressing "filter", "Health Area" that was chosen goes back to "Select Health Area"
- Can we add Export option (csv, xls, pdf) to export a given register?

Question 1: Do all blanks show up as NA? Is there a way to just have it be blank instead?

Question 2: From a user interface perspective, I wonder about the following (see attached): In the component tab, you have an "Action" column with "Edit" and "View" buttons. Similar to this, we could have "Register" and "Report" buttons next to each available one. The user could still filter to get down to which specific Register/Report they are interested in, and then select if they want to view the Register or the Report. This means we only have one tab called Register/Report instead of separate tabs. Does this make sense? 
[RegisterReportUI.pptx](https://github.com/kamal1978/LTFHC/files/4101392/RegisterReportUI.pptx)

**Comment by kamal1978** [comment]
Dheeraj please check and update Ravi.

**Comment by dheerajdutta** [comment]
Ok Sir

**Comment by space-ravi** [comment]
I see progress. I'm not sure if you are done, but here are some comments. Please make sure to tell me when it is complete so I can review: 
- I don't see patients in any of the registers (even though the report has values)
- The download options (csv, excel, pdf) should look like the icons that you already have if I click report. 
- Name for this tab should be "Register/Report" instead of just "Report".

**Comment by dheerajdutta** [comment]
I'am working on this. It will take some time.

**Comment by space-ravi** [comment]
Please provide a date for completion so I can report to LTFHC (I have a meeting with them Tues morning (28-Jan) Central Time.

**Comment by dheerajdutta** [comment]
I will try to complete this before 4-feb-2020.

**Comment by dheerajdutta** [comment]
Done, Pleas check and let me know.

**Comment by space-ravi** [comment]
- I don't see patients in any of the registers (even though the report has values)
- The download options should include all of csv, excel, pdf. I only see csv. 
<img width="1552" alt="Screen Shot 2020-02-17 at 4 23 02 PM" src="https://user-images.githubusercontent.com/9537700/74693736-e7dfa680-51a1-11ea-8110-5efb763554f2.png">

**Comment by dheerajdutta** [comment]
Done, please check.

**Comment by space-ravi** [comment]
It looks exactly the same as my previous screenshot. Are the updates in the demo server?

**Comment by dheerajdutta** [comment]
Yes, Please check on demo server.

**Comment by space-ravi** [comment]
Some comments: 
1. Please change the tab name from "Registers/Report" to "Registers/Reports". 
2. Download pdf is not working
3. File name when downloading: Can we have the default filename for a download be: YYYY-MM_Register_HZ_HA.extension
where YYYY is year of register, MM is month of register, HZ is health zone, HA is health area, and extension is either csv, xls, or pdf?

Please follow a similar format for the report, where Register is replaced by Report.

**Comment by space-ravi** [comment]
Note: I deleted my previous comment saying to push to prod. I found a few things I would like changed first. See above comment.

**Comment by dheerajdutta** [comment]
Point 1 and point 3 has been done. I'm working on **Point 2**, Pdf file is not generating because of which library we are using is not able to handle large amount of data. 
Please check on your demo server.

**Comment by space-ravi** [comment]
On point 3 you did not do this part: Please follow a similar format for the report, where Register is replaced by Report.

**Comment by dheerajdutta** [comment]
> Please follow a similar format for the report, where Register is replaced by Report.

I didn't understand what exactly you need. could you please explain about it.

**Comment by space-ravi** [comment]
You updated the filenames for registers. Please do the same for reports: 

Default filename for a download be: YYYY-MM_Report_HZ_HA.extension
where YYYY is year of report
MM is month of report
HZ is health zone
HA is health area
and extension is either csv, xls, or pdf

**Comment by dheerajdutta** [comment]
Done.

**Comment by space-ravi** [comment]
Thanks. How difficult do we think a pdf of the register will be? It is not high priority so we can descope that for now and come back to it later if we need to. Let me know your thoughts. I would rather the bugs get resolved.

**Comment by space-ravi** [comment]
Please let me know this today so we can either push to prod or wait until the pdf is created before pushing.

**Comment by dheerajdutta** [comment]
I'm working on it. I will try to complete within two working days.
