### ISSUE TITLE
Admin report month is wrong

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#267]
There is an issue with the reports on the prod admin site: http://whpeportal.org/ltfhcdynamic/admin/index.php

The most recent entry (today) shows July 2019 on the menu page. But when you click that report, it shows the last uploaded date is June 28, 2019. This should be a June report. That same village shows a June report and I am wondering if that is actually May. 

Since the health workers use this to populate reports to the government, this should be remedied ASAP.

**Comment by space-ravi** [comment]
Ravi to try to replicate this.

**Comment by space-ravi** [comment]
Here is how the admin report should appear: 
- When clicking on a report, the month listed in the month column in the table should be the month of the data from the register. So the Nov 2019 report should contain data from the register for Nov 1-30 2019.
- If a health worker uploaded data on 5 Nov 2019, any reports for previous months (e.g. Oct 2019) should list the report as "Report complete". The Nov report should be listed as "Report uploaded till 05-Nov-2019".
- A report should not be marked complete until the user has uploaded data past the end of the month. For example, the Nov 2019 report cannot be complete unless the health worker has uploaded data from the tablet in December 2019.

**Comment by space-ravi** [comment]
Has there been progress on this? Please let me know when it is complete so I can verify.

**Comment by dheerajdutta** [comment]
Done, please check and let me know. I have added a new field in display report "next entry:" for testing purpose.

**Comment by space-ravi** [comment]
Thanks, but now I am confused. On the [demo](http://159.65.230.143/ltfhcdemo/admin/index.php?page=report&action=view) site, all the reports are from June or prior. But when I click them, they say data is uploaded in Sept. Are we now only showing completed reports? Before we were showing all reports even if they were not complete.

**Comment by dheerajdutta** [comment]
- We are showing all reports.

- When user uploaded data on 25-feb-2020, every reports of all previous months will be shown as **Report complete**.

- If you click on February report. It will be shown as **Report uploaded till 25-feb-2020**.

Please check and let us know.

**Comment by space-ravi** [comment]
The demo server does not have data after June 2019. What am I missing? 
<img width="1792" alt="Screen Shot 2020-02-28 at 10 25 18 AM" src="https://user-images.githubusercontent.com/9537700/75575263-b32ae500-5a14-11ea-8d8e-80e4d0f708b0.png">
