### ISSUE TITLE
Images are stretched on screen

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#27]
When uploading an image, the image appears stretched on screen. Would like to preserve the aspect ratio of the image (or be able to define this in the attributes section). 

For example. see image here: 
http://103.225.41.0/ltfhcdynamic/admin/index.php?page=component&search_screen_id=20&start=&action=edit&id=50

**Comment by space-ravi** [comment]
Pawan to ask Nidhi: 
1. Is there a reason it is stretched?
2. How can I change the attributes to make sure it keeps the original aspect ratio?

**Comment by ravi-timshel** [comment]
Pawan says this is fixed, Ravi to check.

**Comment by space-ravi** [comment]
Remove weight, remove ScaleType
To increase size of image: provide width, it will automatically adjust height (or vice versa).
