### ISSUE TITLE
Maternity Report

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#270]
Please see attached for the Maternity report. Let me know if you have any questions. 

Note that the top 2 tables are for English language. The bottom 2 tables are for French and Swahili (same tables for both).

Reminder that the report should be implemented for both app and admin website.
[Maternity Report Calculations.pdf](https://github.com/kamal1978/LTFHC/files/3611718/Maternity.Report.Calculations.pdf)

Note there is already a screen called "Maternity Report"

**Comment by kamal1978** [comment]
Ravi can you send invitation to vishalchaurasiya@whpindia.org, for him to see this list of issues, he is the android dev.

**Comment by kamal1978** [comment]
@whpVishal , please create this report, if you need any help on this you can post in here for Ravi to review and answer

**Comment by whpVishal** [comment]
@space-ravi  the Component Array for maternity report is blank please update and let me know

**Comment by space-ravi** [comment]
I'm not sure I understand what you mean by component array. Please clarify. The attachment contains the component IDs that you should use in your calculations.

**Comment by space-ravi** [comment]
Issues with the Maternity report: 
- Please capitalize the first letter in "newborns on antibiotics" (Mistake on my part in what I provided you)
- The group in the report related to component 1815 does not work (6 rows)
- The group in the report related to component 1821 does not work (2 rows)

**Comment by space-ravi** [comment]
Please also see the updated equation in the attached red text. Let me know if you have any questions. 

[Maternity Report Calculations v2.pdf](https://github.com/kamal1978/LTFHC/files/3677154/Maternity.Report.Calculations.v2.pdf)

**Comment by whpVishal** [comment]
Changes has been made in new build shared

**Comment by space-ravi** [comment]
Version: "LTFHC 10th Oct.apk"
Data uploaded to server, user rprakash, Oct 11.
Issues with report: 
- "Women with obstetric complications" is not calculating properly. After entering a single patient, "2" was in the report (as if 2 women had obstetric complications). 
- "Newborn kangaroo method" through "Newborns who received resuscitation" still not calculating properly. The single patient I entered had all of these issues. Only "newborns on antibiotics" had a "1" in the report. 
![Screenshot_2019-10-11-09-03-00](https://user-images.githubusercontent.com/9537700/66666700-194dd180-ec06-11e9-9aec-ca6661e67325.png)

**Comment by whpVishal** [comment]
@space-ravi issue was resolved in 14th oct build, also the report calculation and data been stored have few white space mismatch which was affecting the 'Newborn Kangaroo Method'. it is fixed in today's build

**Comment by space-ravi** [comment]
Version: "LTFHC 18th Oct.apk"
Data uploaded to server, user rprakash, Nov 7.
Issues with report:
- "Deliveries" (first line of report) is not calculating properly. 
- "Newborn deaths ≤ 7 days" is not calculating properly
- "Newborn deaths ≤ 28 days" is not calculating properly

**Comment by whpVishal** [comment]
@space-ravi 
Issues in report
- Deliveries (it is resolved) i will be sharing in next build
- "Newborn deaths ≤ 7 days" and "Newborn deaths ≤ 28 days" for these in 'Maternity Report calculation' it is mentioned 
( if component 1821 = "Die ≤ 7 days" or "Décès ≤ 7 jours", then ++)  and
(if component 1821 = "Die ≤ 28 days" or "Décès ≤ 28 jours", then ++)
but in the field options there is only (Yes|No)
Please check the options, if it has to modify.

**Comment by space-ravi** [comment]
Ack! Good catch. Attached is the updated equations in red. 

[Maternity Report Calculations v3.pdf](https://github.com/kamal1978/LTFHC/files/3826565/Maternity.Report.Calculations.v3.pdf)

**Comment by space-ravi** [comment]
Thanks for catching another mistake. Updated equations attached. 
[Maternity Report Calculations v4.pdf](https://github.com/kamal1978/LTFHC/files/3839288/Maternity.Report.Calculations.v4.pdf)
