### ISSUE TITLE
CPoN Report

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#271]
Please see attached for the CPoN report. Let me know if you have any questions.

Note that the top table is for English language. The bottom table is for French and Swahili (same tables for both).

Reminder that the report should be implemented for both app and admin website.

Note there is already a screen called "CPoN Report"
[CPoN Report.pdf](https://github.com/kamal1978/LTFHC/files/3665111/CPoN.Report.pdf)

To be clear, the reports should not calculate just language specific. If HCW A is using English, and HCW B (same login ID) is using French, the report should include both languages when doing the calculations for the report. Please let me know if this is not clear.

**Comment by space-ravi** [comment]
The CPoN report seems to have the OBGYN report. Please instead add the CPoN report provided in the attachment above.

**Comment by whpVishal** [comment]
Changes has been made in the new build

**Comment by space-ravi** [comment]
Version: "LTFHC 10th Oct.apk"
Data uploaded to server, user rprakash, Oct 11.
Issues with report:
- Bottom 6 rows of report are not calculating properly (only first 3 rows which come from the same component value are calculating properly)
- Please delete the dark blue row in the table that has "Number" (delete the entire row, so we should go from "2.6 Post Natal Care" to "CPoN 1 (6th hour).

**Comment by whpVishal** [comment]
@space-ravi issue was resolved in 14th oct build

**Comment by space-ravi** [comment]
Sorry but I noticed a mistake in one of my equations. Please see the updated equation in red. 
[CPoN Report v2.pdf](https://github.com/kamal1978/LTFHC/files/3821580/CPoN.Report.v2.pdf)

**Comment by whpVishal** [comment]
changes has been made and APK is shared
