### ISSUE TITLE
Is "upload" or "download" working?

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#273]
On the "LTFHC 19th Sep.apk" file, I am not sure that the "upload" or "download" feature is working. I uploaded data to the server. I then deleted the app, cleared the data, reinstalled the apk file. When I press "download", I don't see any patient data for rprakash in any of the registers.

**Comment by whpVishal** [comment]
it is working, tested on different users too

**Comment by space-ravi** [comment]
Something is not working here. I upload data. Then, if I wipe the data from my tablet, press "download", none of the data is there (user rprakash has no patients for any registers).

**Comment by whpVishal** [comment]
@space-ravi As per now the patient details exceeded over actual heap size which was preventing the data to extract and show over api. now you can download it. All the data's which were uploaded previously were successfully inserted.

**Comment by whpVishal** [comment]
@space-ravi The patient data which is under provider 'rprakash' is now coming with 14,00,000+ Json objects which is making the API to response slow. we made few changes on app and api side. it is working properly now.
