### ISSUE TITLE
Family Planning Report

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#278]
Please create the Family Planning report. 

- The screen in the demo admin is called "FP Report".
- The layouts already exist. 
- You should not write the highlighted part (language)
- Many of the cells are intentionally left blank. Do not write the words "leave blank"
- Note there are separate attachments for English and French (Swahili should use French).
- Create for app and for admin site.

[ENGLISH Family Planning Report.pdf](https://github.com/kamal1978/LTFHC/files/4331760/ENGLISH.Family.Planning.Report.pdf)

[FRENCH Family Planning Report.pdf](https://github.com/kamal1978/LTFHC/files/4331761/FRENCH.Family.Planning.Report.pdf)

**Comment by whpVishal** [comment]
Report is added in new build

**Comment by space-ravi** [comment]
1 design issue:
- Table shading below "3.2 Use of family planning methods" has 2 shades. (see attachment)

1 calculation issue (tested in English, please also check in French): 
- New accepting patients under 20 years: This is not calculating correctly. 

![Report issues](https://user-images.githubusercontent.com/9537700/92636456-3ebae380-f28c-11ea-8314-d1e71c49b34d.png)

**Comment by whpVishal** [comment]
The changes has been made in latest build
