### ISSUE TITLE
Unnecessary popup

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#28]
When editing a screen/layout/or component, a popup comes up that says "Data has been updated successfully". This is in addition to the color wheel. These are redundant. Please remove the popup box. 

![screen shot 2017-01-29 at 9 27 53 am](https://cloud.githubusercontent.com/assets/9537700/22406284/4ba9e722-e605-11e6-8d77-376991c7e65a.png)

**Comment by space-ravi** [comment]
Issue still persists on [Screen](http://103.225.41.0/ltfhcdynamic/admin/index.php?page=screen&action=view)/[Layout](http://103.225.41.0/ltfhcdynamic/admin/index.php?page=layout&action=view)/[Component](http://103.225.41.0/ltfhcdynamic/admin/index.php?page=component&start=&action=view) List pages if you show/hide the screen/layout/component.

**Comment by whppawan** [comment]
Done
