### ISSUE TITLE
Admin register: freeze header row and first few columns

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#281]
On the Production admin website: http://159.65.230.143/ltfhcdynamic/admin/index.php

On the registers/reports tab, when you view any register and scroll down, it would be nice if the header row of the table was frozen so that you continue to see it no matter which patient you are looking at.

Likewise, it would be nice if the Columns from 1 through to the family name (first 7 columns) were frozen so that if you scroll to the right, those stay in place.

**Comment by kamal1978** [comment]
Dheeraj is working on it will be done by monday

**Comment by dheerajdutta** [comment]
Done, On the [demo](http://159.65.230.143/ltfhcdemo/admin/index.php) site. Only header row of the table are freeze. Freeze few columns will take some time.

**Comment by space-ravi** [comment]
Thanks. Header looks good. Please push that feature to prod. I will leave this open until the columns are frozen (but consider that low priority).

**Comment by space-ravi** [comment]
Please push to prod.

**Comment by dheerajdutta** [comment]
Done

**Comment by space-ravi** [comment]
Thanks, I will open another ticket to freeze the columns so that we can close this one out.
