### ISSUE TITLE
Admin: use more real estate

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#282]
On the production admin website: http://159.65.230.143/ltfhcdynamic/admin/index.php
On the Registers/Reports tab, when I click any Register, only half the computer screen is used. We should be using a larger window. See image below.

<img width="1792" alt="Screen Shot 2020-03-25 at 9 00 32 PM" src="https://user-images.githubusercontent.com/9537700/77609026-10169f80-6edc-11ea-826b-094c665dff5a.png">

**Comment by kamal1978** [comment]
Dheeraj is working on it will be done by monday

**Comment by space-ravi** [comment]
Wondering if this stalled because of COVID-19?

**Comment by dheerajdutta** [comment]
Done, On the [demo ](http://159.65.230.143/ltfhcdemo/admin/index.php)site.

**Comment by space-ravi** [comment]
Is there an easy way to make it responsive so it uses the whole tab (no matter what size the user has it sized to)? For me, it doesn't look much bigger than before (see attachment).
<img width="1792" alt="Screen Shot 2020-06-09 at 6 04 14 AM" src="https://user-images.githubusercontent.com/9537700/84150934-6f824700-aa17-11ea-8ab3-a15426d0fcc6.png">

**Comment by dheerajdutta** [comment]
Done, please check again. Now it will work on all screen size.

**Comment by space-ravi** [comment]
Great thanks. Please move to prod. I will close the ticket when it is moved over.

**Comment by space-ravi** [comment]
Reminder to move to prod.

**Comment by dheerajdutta** [comment]
Done
