### ISSUE TITLE
Bringing patient data over to DEMO server

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#287]
Is it possible to put patient data from production admin server over to demo server (while leaving the screens on the demo server untouched)? If so, that would be desired so that we have a fresh recent data set to test with.

**Comment by space-ravi** [comment]
Note that I said development server, but I meant DEMO server. I edited the above to reflect the intent.
If you are trying this out, please first make a backup of the demo server. There is a lot of data there that I don't want to get messed up!

**Comment by kamal1978** [comment]
This is done
