### ISSUE TITLE
Register and Report filename mod

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#288]
The user can download csv, xls, pdfs of the registers and reports. I would like to request an additional stem to the filenames (additional part is ABCDE which I define below).

**Reports:** 
Default filename for a download: YYYY-MM_ABCDE_Report_HZ_HA.extension
where YYYY is year of report
MM is month of report
**ABCDE is the department of the report (e.g. Prenatal)**
HZ is health zone
HA is health area
and extension is either csv, xls, or pdf

**Registers**
Default filename for a download: YYYY-MM_ABCDE_Register_HZ_HA.extension
where YYYY is year of register
MM is month of register
**ABCDE is the department of the register (e.g. Prenatal)**
HZ is health zone
HA is health area
and extension is either csv, xls, or pdf

**Comment by dheerajdutta** [comment]
Done, please check.

**Comment by space-ravi** [comment]
I don't see this implemented. I checked both prod and demo admin websites. Where is the change?

**Comment by dheerajdutta** [comment]
![image](https://user-images.githubusercontent.com/43786726/90624550-c1282880-e235-11ea-8d5a-996ad1d8328e.png)

@space-ravi, this changes was already done. The format of the file is **2020_June_Register_Nyemba_Kituku.xls** (YYYY-MM_ABCDE_Register_HZ_HA.extension).

**Comment by dheerajdutta** [comment]
@space-ravi Please check once again.

**Comment by space-ravi** [comment]
Hi @dheerajdutta - the request was to add the department name between the month and the word "Report" or "Register". So in the example you emailed me, it should be 2020_June_Prenatal_Register_Nyemba_Kituku.xls

**Comment by dheerajdutta** [comment]
Done, Now the format is 2020_June_Prenatal-Department_Report_Nyemba_Kituku.xls. Please check.

**Comment by space-ravi** [comment]
Thanks looks good. Just to be clear, the department is auto-populated? So when we have other departments, it will automatically adjust?

**Comment by dheerajdutta** [comment]
Yes
