### ISSUE TITLE
Add ability to delete screen/layout/component

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#29]
Right now, screens/layouts/components can be hidden, but not deleted. Is it possible to have the option to delete a screen/layout/component as well? 

If so, the desired icons are (these icons should be next to the edit button, where the green checkmark and red x currently are): 

Hidden: 
![eye-outline-off-1](https://cloud.githubusercontent.com/assets/9537700/22410880/8795a5e4-e652-11e6-8236-1aa17e4ed04d.png)

Visible: 
![eye-1](https://cloud.githubusercontent.com/assets/9537700/22410884/8cae4130-e652-11e6-9221-d803a99f5b81.png)

Then, the red x you have can be next to the hidden/visible toggle. If clicked, a popup should appear that asks "Do you want to delete the screen/layout/component? All associated content will also be deleted.". After clicking OK, the item will be deleted permanently. 

If a screen is deleted, all layouts/components associated with that screen should be deleted. If a layout is deleted, all components associated with that layout should be deleted.

**Comment by space-ravi** [comment]
Note: When the admin presses the "Delete" icon, it should remove the item from the admin. However, the item should not be deleted from the database.

**Comment by space-ravi** [comment]
This item is lower priority than the others.

**Comment by whppawan** [comment]
First part is done.
Removing the item from the list is remaining.

**Comment by ravi-timshel** [comment]
Update: Will be completed after pilot starts.
