### ISSUE TITLE
Remove patient PII from admin website

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#296]
We would like to remove PII from the PROD admin website (is it easy to do just on prod. and stay that way when we update new features from demo?). 

In the register, please remove:
- Given Name
- Family Name

I'm also wondering how hard (or not) this is to do since I think you mostly mirror the tablet register?

**Comment by dheerajdutta** [comment]
Done, On the [demo ](http://159.65.230.143/ltfhcdemo/admin/index.php) site. Please check and let me know.

**Comment by space-ravi** [comment]
Looks good. Please push to prod.

**Comment by space-ravi** [comment]
Please push to prod.

**Comment by dheerajdutta** [comment]
Done
