### ISSUE TITLE
Admin screen sorting

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#30]
How are the screens sorted [here](http://103.225.41.0/ltfhcdynamic/admin/index.php?page=screen&action=view)?

Same for layout/component on their respective pages?

**Comment by space-ravi** [comment]
Screen: Please make it alphabetical by name. 
Layout: Please sort by screen then sequence. 
Component: Please sort by screen, then layout, then sequence.

**Comment by whppawan** [comment]
Done
