### ISSUE TITLE
CPS and CPS Vaccination report translation fixes

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#300]
The CPS and CPS Vaccination reports in the tablet app have several translation fixes that are needed for the French version. Please see BOTH tabs of the attachment. Items in yellow are changes that are needed for the French version only. 

[CPS.Registers.vs.report.SNIS.English.-.rp.2020-06-30.Beaconpath.xlsx](https://github.com/kamal1978/LTFHC/files/4853888/CPS.Registers.vs.report.SNIS.English.-.rp.2020-06-30.Beaconpath.xlsx)

**Comment by space-ravi** [comment]
It looks like the changes were not made to the CPS Vaccination report (see 2nd tab of attachment).

**Comment by whpVishal** [comment]
i totally missed the second tab in last build, sending the changes in new build.
