### ISSUE TITLE
Inefficient use of images

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#304]
Issue: 
- The field team often doesn't see arrows and home buttons on APK file
- Takes a long time to download data 

A proposed fix for this (let's chat about this...)
- Right now, we are using the same icons on the screen (home, backward arrow, forward arrow)
- However, the app downloads these images for each screen, therefore, there are hundreds of these images when there only needs to be 3.
- Can we have a way of automatically using the same icon (maybe if the component name is "Backward" it knows to use the backward arrow)?

This might help solve both issues.

**Comment by whpVishal** [comment]
Hello Ravi, 
     Yes , It is possible and can be done from app side there will be no need to download all similar icons.

**Comment by space-ravi** [comment]
Ok thanks. I will set up a call for us to talk through the logistics.

**Comment by space-ravi** [comment]
Globalize images, call global values (not local values). This will reduce download size.

**Comment by space-ravi** [comment]
Closing this issue. Opening a new issue that is a more generic app structure update to increase efficiency of the app.
