### ISSUE TITLE
Register not in chronological order

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#309]
The registers should be displaying patients in chronological order (oldest on top). This is not always happening. For example, see Undugu April 2020 register, entry 55 is 2020-Apr-14, and entry 56 is 2020-Apr-10. 

Also worth noting, there is a lot of data in this register I would not expect to see in here (I am following up with health workers and field team to understand). But I wonder if this is a technical issue who's effect is putting data in non-chronological order. If you look at monthly number, you'll notice that they are mostly in order, but then you get a block of entries with seemingly random monthly numbers (red text, see attachment). 

Let me know if you want to talk about this.
[2020_April_Register_Nyemba_Undugu.xlsx](https://github.com/kamal1978/LTFHC/files/5032523/2020_April_Register_Nyemba_Undugu.xlsx)

**Comment by dheerajdutta** [comment]
Done, Please check ([demo_server](http://159.65.230.143/ltfhcdemo/admin/index.php)).
