### ISSUE TITLE
OBGYN report calculation issue

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#310]
Using APK file: "LTFHC demo 21st July.apk"

French language, OBGYN report, user: rprakash
I did not enter any patients into the register for August. The register is empty (as expected). 
When I view the August report, there are "2's" in each entry.
I attached the calculations in case that helps.

Screenshot of register, showing no patients entered in Aug 2020
![Register](https://user-images.githubusercontent.com/9537700/89493542-3fca9380-d769-11ea-858a-5e2297bd3cc3.png)

Screenshot of Aug 2020 report, showing 2's in each row:
![Report](https://user-images.githubusercontent.com/9537700/89493567-507b0980-d769-11ea-8635-f6b0309919ab.png)
[OBGYN Report.pdf](https://github.com/kamal1978/LTFHC/files/5032712/OBGYN.Report.pdf)

**Comment by whpVishal** [comment]
Changes has been done in new build.
