### ISSUE TITLE
CPS report calculation issue

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#311]
Similar to issue #310, without any patients in the French CPS register for Aug 2020, the report shows large values for the first row of the register. Also, the 0's are placed seemingly randomly. 

![Screenshot_2020-08-05-22-28-28](https://user-images.githubusercontent.com/9537700/89494591-54a82680-d76b-11ea-8aa1-f18d7dfcf4dd.png)

**Comment by whpVishal** [comment]
Changes has been done in new build
