### ISSUE TITLE
Create "Operating" Report

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#313]
Please create the Operating block report (see attached):

The screen in the demo admin is called "Operating Report".
See attachment: blue is English, red is for French and Swahili
Create for app and for admin site.

[Operating Block Report.xlsx](https://github.com/kamal1978/LTFHC/files/5198086/Operating.Block.Report.xlsx)

**Comment by space-ravi** [comment]
Slightly updated (translation fixes) in this version: 
[Operating Block Report v2.xlsx](https://github.com/kamal1978/LTFHC/files/5324163/Operating.Block.Report.v2.xlsx)

**Comment by whpVishal** [comment]
The changes has been made in latest build.

**Comment by space-ravi** [comment]
Issues: 
- The "Urgent" column keeps incrementing even when Component 2698 is "Scheduled"

Note to self: Due to issue 319, I cannot check the rest of the report calculations. I still need to check sections 11.2 and 11.3.

**Comment by whpVishal** [comment]
Changes has been made in new Build shared today.

**Comment by space-ravi** [comment]
Issues: 
- Section 11.3 of the report. I had a single user that had component 2713 = "Other general anesthesia". The item did not increment as it should have. 

Please check the equations in Section 11.3 of the report.
