### ISSUE TITLE
Issue with format of downloaded excel file

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#317]
See prod admin, 2020_September_Prenatal-Department_Register_Kalemie_Kataki

Download the excel file. You'll notice that row 3 is broken up during column F, and the rest is in row 4. See attached. 
[2020_September_Prenatal-Department_Register_Kalemie_Kataki.xls.zip](https://github.com/kamal1978/LTFHC/files/5293168/2020_September_Prenatal-Department_Register_Kalemie_Kataki.xls.zip)

**Comment by dheerajdutta** [comment]
User **pressed the enter key twice** while entering data therefore row 3 had broken up during column F. Now this issue has been solved, please check.

**Comment by space-ravi** [comment]
Was the issue solved because you deleted the extra "enter" press? Or was the issue resolved because you developed a fix in case any user does this again?

**Comment by dheerajdutta** [comment]
I have resolved this issue in the "**Health Area**" field. When the user presses the "**enter**" key, the system will convert them into "**space**".
