### ISSUE TITLE
CPS Vaccine Report update

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#318]
There is a slight update with the CPS Vaccine report. Please see the updated equations and headings in the attachment (highlighted in yellow). Basically, we are adding another option for the French version of Male and Female. Only French language is affected. 
[CPS_Vaccine_Registers-2020-10-04.xlsx](https://github.com/kamal1978/LTFHC/files/5325198/CPS_Vaccine_Registers-2020-10-04.xlsx)

**Comment by whpVishal** [comment]
This one is Fixed in new Build.
