### ISSUE TITLE
APK app crashing in Operating register

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#319]
2020-Oct-06 APK file keeps crashing in the Operating register. 
I am signed in as user: ekalwele (password: kataki). I am using English language.

In the operating register, I entered a patient in the register. Then, I view register, click the single patient in there, click "Edit" on the patient summary. Then, I leave the previous values in there and press OK on each screen. When I get to the "Intervention" screen (asking if Major or Minor intervention), either button I click causes the app to crash. 

This is very repeatable from my side. I have uploaded the data to the server.

**Comment by whpVishal** [comment]
Changes has been made in new Build shared today.
