### ISSUE TITLE
APK for logic does not allow me to download data

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#324]
Using LTFHC_dev_13th_oct.apk
On the tablet app when I press "download", this is the error I get...
Therefore I cannot test the logic capability that I am adding. 

![Screenshot_2020-10-17-09-58-40](https://user-images.githubusercontent.com/9537700/96349814-d9b29480-1066-11eb-8ae8-dc0ae5e58875.png)

**Comment by whpVishal** [comment]
this issue has been solved in latest build.
