### ISSUE TITLE
Logic doesn't seem to work if you go back to a question

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#325]
The screen I am testing logic on is Prenatal Address. See the conditions in the attached. 

If both conditions are not met, the screen should go to patient weight (instead of patient address). It seems that if I go back and modify the patient's age, the logic does not work as it should. 

![Screen Shot 2020-10-17 at 11 43 21 AM](https://user-images.githubusercontent.com/9537700/96351078-0027fe00-106e-11eb-96aa-de1b4ebd923e.png)

**Comment by whpVishal** [comment]
This issue has been solved in latest build.

**Comment by space-ravi** [comment]
Using LTFHC_dev_22nd_oct.apk, logic is not working at all. Please make sure that the example I have shown in the original post works.

**Comment by whpVishal** [comment]
Hi Ravi,
     There was a Numeric casting issue in the last build which i just find out. This issue is fixed in new build i shared today
