### ISSUE TITLE
Admin site redesign

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#326]
**This should be complete by Nov 6**

As part of the branding for the app, LTFHC would like the admin website to match the new brand. Please see the attached for what we are proposing. We took care to minimize the changes to the existing design, mostly changing colors, font, and the like. 

- Slide 1: Desired admin landing page
- Slide 2: Desired page after logging in
- Slide 3-4: Current admin page with markups (specifying colors, fonts, wording changes, etc)

Please let me know if you need anything else.

[Admin website redesign v3.pptx](https://github.com/kamal1978/LTFHC/files/5436790/Admin.website.redesign.v3.pptx)

[Iroko admin webpage icons.zip](https://github.com/kamal1978/LTFHC/files/5436787/Iroko.admin.webpage.icons.zip)

**Comment by dheerajdutta** [comment]
@space-ravi, In slide 2 you are showing only two **tabs** (**Registers/Reports** and **Change Password** ). What about the other **tabs** ? Please let me know so i can proceed further.

**Comment by space-ravi** [comment]
Excellent question! In general, all tabs should follow the same general rules of thumb: 
- All font should be Open Sans Regular
- Header bar should use color #005A70
- Buttons colors above the tables (like "Add New" and "Filter" should be 00B74F
- Button colors within the tables (like "Report" or "Edit") should be E35205
- If it is easy to do, the icons in the tables (like the trash can and eye) should also be E35205
- On tabs that have filters (like layout or component tabs), match the color/style of the filter box on the registers/reports tab

Let me know if you have any additional questions. The highest priority tabs are the register/report tab and the change password tabs since those are customer facing tabs.

**Comment by dheerajdutta** [comment]
@space-ravi , Please check this [link](https://whpeportal.org/ltfhcdynamic_23_10_2020/) and let me know.

**Comment by space-ravi** [comment]
This looks great! Thanks for the quick turnaround. I really appreciate it. Some comments: 
Login page: 
- I notice in the webpage tab, it has a WHP logo. Can that instead be the Iroko_Health_symbol_rgb_cw icon?
- Some reason the green circles on the logo look bright green on the webpage, but are not as bright in the file. Are you also noticing that?
- Login and Password boxes - can we make the font bigger?
- "Submit" and "Forgot Password" should be on the same position vertically (right now, forgot password is higher than submit).
- Submit button: please increase the padding on all sides (to try to make it look like the example). The gmail sign-in page is a good example of what I'm looking for (attached).
- Can we make the bottom green bar (footer) the same height as the header green bar? And bold the words?
- ONLY if this is easy: can we have the logo+sign in box be centered vertically (and responsive so that no matter what size the screen is, it is always vertical?). Similar to how it is currently responsive horizontally.

After logging in: 
- The font should be Open Sans Regular
- Please increase the size of the font in the top header (Screen, Layout, etc)
- The buttons (Report/Register/Filter) - I actually prefer the size/shape of the buttons that you previously had, I just wanted the color and font of the buttons to change (that's what I meant by "keep your button size/shape" on slide 4)
- On the "User" tab, I like the spacing of the icons (edit, eye, trash). Can you please use that same spacing for the Screen, Layout, Component, and Location tabs?
- Can you switch the order of the "Role" tab to be before "Registers/Reports"?
- Can we have a little more margin between the "Report" and "Register" buttons? 
- User tab: the "Add New" button is title case. On the other tabs, it is all upper case. I like the upper case look. Can you please update it to match? 

<img width="506" alt="Screen Shot 2020-10-27 at 6 34 53 AM" src="https://user-images.githubusercontent.com/9537700/97308840-8be41c00-181e-11eb-837a-f6897d786612.png">

**Comment by dheerajdutta** [comment]
All changes has been done. Please check this [Link](https://whpeportal.org/ltfhcdynamic_23_10_2020/) and let me know.

**Comment by space-ravi** [comment]
Hi Dheeraj,

Thanks again for the quick turnaround. This is looking very good. Some comments: 

Login page:
- Webpage tab, I asked you to put Iroko_Health_symbol_rgb_cw icon (which you did). Can you please change this out with Iroko_Health_symbol_cmyk.ai (attached)?
- One of my previous comments was a goof. Please revert the color of the header and footer bars on the login page back to 005A70. (I don't know why I said green).
- The Submit button seems to have some shadowing effect. Can you just make it a flat button? Like the Filter button on the register/report page? 

After logging in: 
- The font should be Open Sans Regular. It is still a Serif font.
- Can you please double check that the font size on the header (Screen, Layout, etc) are all the same size? It might be my eyes playing tricks on me, but "Screen" looks like a smaller font size than "Registers/Reports".
- I like how on the login page, the footer text (better health starts with better data) is bolded. Can you do the same here?
- Report/Register buttons: Can we have a little top/bottom margin between buttons so that it doesn't look like the buttons are touching each other? I think the horizontal spacing you have between "Report" and "Register" buttons is good. 
- Font size on the table header (Item, Department, etc) - can you make this the same font size as the filter options (Select Department, Select Health Zone, etc)?


[Iroko_Health_symbol_cmyk.ai.zip](https://github.com/kamal1978/LTFHC/files/5461746/Iroko_Health_symbol_cmyk.ai.zip)

**Comment by dheerajdutta** [comment]
Hello Mr. Ravi,

Thank you for your appreciation.

All changes has been done.

Login page:

**1.** "Open Sans" was not working here. Now this issue has been solved here also.

After logging in:

**1.** I have checked, the font size of all "Header's Tabs" ( Screen, Layout, Component, Location, User, Role, Registers/Reports, Change Password, Logout) are the same.

**2.** Font size of table header (Item, Department, etc) and filter option (Select Department, Select Health Zone, etc) are the same.         The only difference is the table header (Item, Department, etc) is bold. should i have to remove the bold  from table header (Item, Department, etc)?

**Comment by space-ravi** [comment]
This looks so good! 1 more hopefully small thing: 

On the register/report tab, can you freeze the table header so that as the user scrolls, it will remain visible? I think the filter should also always remain visible, so maybe the solution is just to put a scroll bar in the table itself? Thoughts?

**Comment by dheerajdutta** [comment]
Done.

**Comment by space-ravi** [comment]
Great!  I see the table is a fixed height. Is there an easy way to have it expand with the screen size? See example screenshot... Ideally the height of the table would fill my window no matter what the size. (If this is difficult, then we can just close out this issue for now). 

![Screen Shot 2020-10-30 at 12 11 21 PM](https://user-images.githubusercontent.com/9537700/97747462-3f604100-1aa9-11eb-9ebb-fca55bb6afbd.png)

**Comment by dheerajdutta** [comment]
No, it is not difficult because I did  this at the register table. It has been done, please check.

**Comment by space-ravi** [comment]
Your response time is amazing, thank you!  Don't work too late! 😄
