### ISSUE TITLE
App splash page changes

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#327]
To be consistent with the iroko health branding, we would like to update the splash page on the app. Please see the attached. Updates include: 
1. Logo change
2. Modify WHP to 18Logic

This change is to be made to demo server only. (not production just yet)

Desired icon is attached.

[App splash page redesign.pptx](https://github.com/kamal1978/LTFHC/files/5432086/App.splash.page.redesign.pptx)

[Iroko_Health_h_cmyk.ai.zip](https://github.com/kamal1978/LTFHC/files/5436746/Iroko_Health_h_cmyk.ai.zip)

**Comment by space-ravi** [comment]
The logos look a bit stretched. Can we keep the original aspect ratio of both images (app logo and 18Logic logo)?

**Comment by whpVishal** [comment]
i have changed it back to original ratio.
