### ISSUE TITLE
Translations on admin website (for French)

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#332]
Please remind me: For translations on the admin website, do we have control over all the words? Or some of the words are being automatically translated and we don't have control over those? 

LTFHC has requested the following translation fixes when in the **French** language:
On the register/report tab, the filter options row should have: 
- Sélectionner l' Département should be Sélectionner le département
- Sélectionner l' Zone de santé should be Sélectionner la zone de santé
- Sélectionner l' Aire de santé should be Sélectionner l'aire de santé
- Sélectionner l' Année should be Sélectionner l'année
- Sélectionner l' Mois should be Sélectionner le mois

Other items on this tab: 
- Departement Prenatal should be Département Prenatal (in table, in the option in the filter area, also when one clicks the report button it is in the report table)
- Under the month filter, "mars" should be "Mars" (also when one clicks the report button, the mistake is in the table there)
- Under the month filter, "Aout" should be "Août" (also when one clicks the report button, the mistake is in the table there)
- "Report" button should say "Rapport"
- "Register" button should say "Registre"

Further: 
- When one clicks the "Register" button, the header row of the register is in English. It should be in French.
- When one clicks the "Report" button, it may say "Report uploaded till (DATE)". It should say "Rapport téléchargé jusqu'au (DATE)".
- When one clicks the "Report" button, it may say "Report Complete". In those cases, it should say "Rapport Terminé".
- When one clicks the "Report" button, item 2 in the table says "La sant� de la m�re". It should say "La santé de la mère"

Both English and French: 
- When one clicks the "Report" button, the title above the table "Rapport médical mensuel d'ERCC". Please change to "Rapport SNIS mensuel d'Iroko". (In English, please also change title from "ERCC Monthly Medical Report" to "Iroko Monthly SNIS Report".

**Comment by dheerajdutta** [comment]
Hello,

Please let me know if removing "**l'**" from "**Sélectionner l'**" will work for you. If I make changes in code it will take some time because whatever the words are coming from the database. Please let me know, till then I'm working on other part of this issue.

**Comment by space-ravi** [comment]
I’m confused by the question. For example, 

Sélectionner l' Département should be Sélectionner le département
You are just supposed to change the phrase “Sélectionner l' Département” with “Sélectionner le département”. 

Does that answer the question?

**Comment by dheerajdutta** [comment]
I mean to say, In database this "**Sélectionner l'**" stored as a single word. Therefore I'm asking that can i remove the "**l'**" from **Sélectionner l**

**Comment by space-ravi** [comment]
Ah ok. Yes, thanks.

**Comment by dheerajdutta** [comment]
All changes have been done. Row of register which has been  translated into french, please check because i manually entered.

**Comment by space-ravi** [comment]
Mostly good. A few issues:

Registres/Rapports tab
Issues
- "Registres" button should say "Registre" (for each row)

- After clicking the register button, the "Download CSV", "Download Excel" options should be "Télécharger CSV" and "Télécharger Excel".

- For these two items, the fix was made for the filter, but if you click a report for that month, the report shows the unfixed text: 
1. Under the month filter, "mars" should be "Mars" (also when one clicks the report button, the mistake is in the table there)
2. Under the month filter, "Aout" should be "Août" (also when one clicks the report button, the mistake is in the table there)

Login page: 
"mot de passe" should be "Mot de passe"

Other: 
- I didn't realize that when the filter row changed to something like "Sélectionner département", that the table header would end up being lowercase. Can you please return those to capital letters so the table header is Capitalized?

**Comment by dheerajdutta** [comment]
Done.

**Comment by space-ravi** [comment]
Thanks for the quick turnaround, especially on Diwali. 

A couple more minor comments: 
- Registres/Rapports tab, the last column of the table says "View Item". It should instead say "Afficher"
- When you open the report, the top table header is still lowercase

In the register that you entered manually, here are some corrections: 
- "Mensuel numéro" should be "Numéro Mois"
- "Numéro de dossier" should be "Numéro dossier"
- You have "Zone de santé" twice. The second one should be "Aire de santé"
- "Consulter" should be "Visite CPN"
- "Statut VIH connu" should be "Statut VIH connu à l'arrivé"
- "Dépistage de la syphilis" should be "Test de syphilis"
- "Résultat de la syphilis" should be "Résultat Test de Syphilis"
- "CD4" should be "Groupe (Cluster)"
- "Violence de genre" should be "VBG"
- "Vaccin contre le tétanos" should be "VAT"
- "doux" should be "MILD"
- "Plan de naissance" should be "Plan d'accouchement"
- "Patient référant" should be "Référer la patiente"
- "Test VIH pour homme" should be "Test VIH de l'homme"
- "Résultat du post-test" should be "Post test de l'homme"
- "Ménage" should be "Nombre total de famille"
- "Test VIH à domicile" should be "Nombre testes VIH de famille"
- "Résultats" should be "Résultats supplémentaires

**Comment by dheerajdutta** [comment]
I'm glad I could work for you. 

Rest of the changes have been done. Please check.

**Comment by space-ravi** [comment]
Thanks!  Only remaining issue is R�sultat Test de Syphilis should be "Résultat Test de Syphilis"

<img width="1904" alt="Screen Shot 2020-11-16 at 9 21 07 PM" src="https://user-images.githubusercontent.com/9537700/99349786-ab84c800-2851-11eb-8260-d1932a2f6443.png">

**Comment by dheerajdutta** [comment]
Done.
