### ISSUE TITLE
CPS report calculation error

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#333]
APK: 2020-Oct-22
User: rprakash 
I uploaded data to the server.

In the CPS report, I entered a single patient, aged 22 months. The report shows a "1" in the 12-23 months column (as expected), but also a "1" in the < 6 months column (not expected). Please check the calculations and fix. This is a good opportunity to check all the other calculations as well. Thanks.

![Screenshot_2020-10-27-18-32-49](https://user-images.githubusercontent.com/9537700/97379895-25451980-1883-11eb-84fe-5297fba3f700.png)

**Comment by whpVishal** [comment]
Issue Resolved in latest Build
