### ISSUE TITLE
Issue with demo admin site

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#334]
There are 2 issues with the demo admin site: 

1. When I try to make a change to the app via the admin site (for example I am trying to change a component on the "Prenatal Health Area 1" screen), and I click "submit" after making the change, the processing wheel keeps spinning and the changes never go into effect. 

2. When I try to create a new component, I get a different error (Unknown column 'skip_logic_screen_name' in 'field list')

Please make sure I can create new screen/layout/component, and edit existing screen/layout/component.

**Comment by dheerajdutta** [comment]
Done, please check and let me know.
