### ISSUE TITLE
Screens on demo server are not what I previously had

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#335]
The appearance of many of the screens on the demo server are different than what I previously had. Please make sure ALL the screens that I had in demo server are exactly the same. 

For example (just one of many): 
Prenatal Main Menu screen now looks like (2020-Oct-29):
![Screenshot_2020-10-29-17-09-44](https://user-images.githubusercontent.com/9537700/97646272-7f251b00-1a0c-11eb-9491-a266842cc826.png)

But it used to look like (2020-Oct-22): 
![Screenshot_2020-10-29-17-30-13](https://user-images.githubusercontent.com/9537700/97646286-851afc00-1a0c-11eb-9d4b-bad6d465bf73.png)

**Comment by whpVishal** [comment]
This issue has been fixed in new build.
