### ISSUE TITLE
Cannot upload images to demo admin

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#337]
See component ID 3094 (prenatal health area 2 screen, home button). I am trying to upload the usual home button. When I do, instead of the image coming up, I get this (see below). When I go to the screen, there is no home button. 

![Screen Shot 2020-10-30 at 12 00 38 PM](https://user-images.githubusercontent.com/9537700/97746441-8d744500-1aa7-11eb-92ad-ffb28a4b8562.png)

**Comment by dheerajdutta** [comment]
Done, please check. It was the issue of directory permissions.

**Comment by space-ravi** [comment]
Thank you!
