### ISSUE TITLE
Missing home/backward/forward images in admin site

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#339]
All the home/backward/forward arrows are missing from ALL registers (except Prenatal). 
I am attaching the images here.
[LTFHC images.zip](https://github.com/kamal1978/LTFHC/files/5467452/LTFHC.images.zip)

**Comment by dheerajdutta** [comment]
Done.

**Comment by space-ravi** [comment]
I see the images on the admin site, but I don't see them coming up in the app. Adding @whpVishal to this thread.

**Comment by whpVishal** [comment]
Hello Ravi,
     It seems like the images are not assigned in the component. You need to change all the image in the components. 
Ex:
for component name: "CPoN HCW Name", i am getting this image resource in json
"image": "ltfhcdynamic\/\/images\/component\/1597.png", for home button

**Comment by space-ravi** [comment]
Hi Vishal, just to make sure, you are saying I need to go through each component that has an image, and reupload the image? There are hundreds of screens, and each screen usually has 2-3 images. The images were all there prior to updating the demo server with the logic.

**Comment by space-ravi** [comment]
Also, just so we're clear, the images are showing up in the admin (see CPoN HCW Name home button): https://irokohealthportal.com/ltfhcdemo/admin/index.php?page=component&search_screen_id=228&start=&action=edit&id=1597

They are just not showing up in the app. So the problem is not that I haven't already uploaded the images in the past.

**Comment by space-ravi** [comment]
Also, now, when I am uploading new images, they are not appearing. There is definitely an issue on the developer side.

**Comment by dheerajdutta** [comment]
@space-ravi, It may be the issue of **Application url**:

because I had't uploaded images in this URL https://whpeportal.org/ltfhcdynamic_23_10_2020 , now it  has been uploaded to this server also.

**Note:** Perhaps your application and admin site URL are different therefore you faced this issue.

**Comment by space-ravi** [comment]
I am using APK version 30 Oct 2020. All other changes I am making to the admin site are showing up in the app. The images are still not showing up. I am using this admin site: https://irokohealthportal.com/ltfhcdemo/admin/index.php

**Comment by whpVishal** [comment]
Hello Ravi,
     I have been looking on all aspects and I think this is the time to use the single image resource for home, backward and forward buttons. I am sending you a new build for that right away in which I used the attached images you shared.

**Comment by space-ravi** [comment]
Thanks Vishal, it's working now. Some questions: 
1. Are you still using this admin site in this APK file? https://irokohealthportal.com/ltfhcdemo/admin/index.php
2. How are you calling these images? For example, is it anytime there is a component with name "Backward" you call the backward arrow? 
3. Is there any point in me uploading images for home/backward/forward anymore?

**Comment by whpVishal** [comment]
Hello Ravi,
1. Yes, I am using the same URL.
2. The images got defined in components image on web side and at the time of downloading the screens, these images also get downloaded. On behalf of the screens, i read the images name and after that it was then picked from the downloaded images folder and attached to the particular screen components.
3. No, you don't have to worry about it any more for home, backward and forward.
