### ISSUE TITLE
Logic flow issues

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#340]
I am having issues with what I am trying to do: 

- Prenatal Health Zone screen has 3 options (Kalemie, Nyemba, Other). 
- Each option has a different screen as a result. 
- The logic I used was: 
-- "Prenatal Health Area 1" screen shows if "Kalemie" is selected (else show "Prenatal Health Area 2" screen)
-- "Prenatal Health Area 2" screen shows if "Nyemba" is selected (else show "Prenatal Health Area Other" screen)

The issue is that if the user selects "Nyemba", and then presses BACK to the previous screen, then they end up at the Kalemie screen, when I want them to end up at the "Prenatal Health Zone" screen.

A similar issue occurs if the user selects "Other" on the "Prenatal Health Zone" screen and then wants to go back. 

Note that this is sometimes repeatable, but sometimes actually works as desired.

**Comment by space-ravi** [comment]
I ended up removing the logic from the screens described originally (for other reasons), but I am experiencing the same issue with a different set of screens: 
- On the "Prenatal Syphilis Testing" screen, the user selects "YES" or "NO"
- If "YES", then go to "Prenatal Syphilis Positive" screen. Choices are Positive or Negative.
- If "Positive", then go to "Prenatal Syphilis Treatment" screen (else go to "Prenatal Cough" screen)

If the user selects "Yes", "Negative", then they end up on the Cough screen (as expected). Then if they press back, they should go to the "Prenatal Syphilis Positive" screen, but instead it often goes to the "Prenatal Syphilis Treatment" screen.

**Comment by space-ravi** [comment]
Another example: 
- On screen "Prenatal Detected Risks - Bina" the user can select YES or NO
- If "YES", go to "Prenatal Detected Risks" screen, else go to "Prenatal Referring Patient". 

If you select NO, but on the "Prenatal Referring Patient" slide go back, then you end up at the "Prenatal Detected Risks" screen

**Comment by whpVishal** [comment]
Hello Ravi,
     I am sending a new build in which i tested above scenarios. please have a look and let me know.
