### ISSUE TITLE
Issue using string with logic

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#342]
On screen "CPoN Problem Mother-1"
I am trying to enter the logic: 

- If screen "CPoN Visit Number", component "CPoN Visit" equals: "CPON 1 (6e heure)", 
- Then go to the "CPoN Problem Mother-1" screen, 
- Else go to screen "CPoN Problem Mother-2".

When I enter "CPON 1 (6e heure)", and click submit, it changes just to "CPON". Therefore, the logic is not working as expected.

**Comment by dheerajdutta** [comment]
Done.
