### ISSUE TITLE
CPoN Logic flow issues

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#343]
On the CPoN register, I am unable to get the logic to work:
On screen "CPoN Visit Number", the user selects the visit: CPoN 1 (6th hour)|CPoN 2 (6th Day)|CPoN 3 (6th Week)

Desired outcome:
If they select "CPoN 1 (6th hour)", then they will eventually see the "CPoN Problem Mother-1" screen.
If they select "CPoN 2 (6th Day)", then they will eventually see the "CPoN Problem Mother-2" screen.
Else, they will see the "CPoN Problem Mother-3" screen.
After the chosen "CPoN Problem Mother-X" screen, the next screen should be the "CPoN Care" screen

Test case: 
I selected CPoN 2 (6th Day). After going to the "CPoN Problem Mother-2" screen (as expected), the NEXT screen I go to is the "CPoN Problem Mother-3" screen, when I should be going to the "CPoN Care" screen.

**Comment by whpVishal** [comment]
This issue has been fixed in new build i shared.

**Comment by space-ravi** [comment]
For the example I gave above, the app now always go to the "CPoN Problem Mother-3" screen when I select "CPoN 2 (6th Day) in the "CPoN Visit Number" screen. 

I'm not sure if this could be the reason, but when I enter the logic in the "CPoN Problem Mother-2" screen (among other screens), and click "save", it leaves an extraneous space after the condition. So in the "CPoN Problem Mother-2" logic screen, I wrote "CPoN 2 (6th Day)", but after saving, it becomes "CPoN 2 (6th Day) " (notice extra space at end).

**Comment by dheerajdutta** [comment]
I have increased the width of the input field, so that you can easily  view. I have removed the extra space.

**Comment by space-ravi** [comment]
Thanks, but does that mean the logic now works?

**Comment by whpVishal** [comment]
Hello Ravi, I retested the above case and for all 3 options in CPoN Visit number it is working as per condition.
i.e:  

6th hour   ->CPoN1     |
6th day     ->CPoN2      |  ->> CPoN Care
6th week  ->CPoN3     |

Please guide me through if i am missing something.

**Comment by space-ravi** [comment]
Working now, thanks
