### ISSUE TITLE
Prenatal HIV logic not working

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#345]
See screen "Prenatal Man HIV Skip". On this screen, the choices are YES or NO (or in French, OUI or NON). 
If YES, then go to screen "Prenatal age of partner". 
If NO, then go to screen "Prenatal household"

The logic I have in the "Prenatal age of partner" screen is pasted below. I am not sure why it is not working. 

![Screen Shot 2020-11-05 at 8 19 57 PM](https://user-images.githubusercontent.com/9537700/98325722-4f45bc80-1fa4-11eb-8bed-32d70587c530.png)

**Comment by whpVishal** [comment]
Hello Ravi,
     If there is logical condition on any screen components then, You have to select "Save" on the **OnClick** . Only then a particular screen will check for its logical condition fulfilment. 

**Note : ** The Logic will only work on those screens whose value get stored in local Db.


![Untitled](https://user-images.githubusercontent.com/46335366/98346340-d4c87b80-203b-11eb-9cb5-e872ef509d63.png)
