### ISSUE TITLE
Monthly number disappears in Register

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#346]
In the Prenatal (CPS) register, user rprakash, I uploaded data to the server. 

- I entered a patient in the register (monthly number 1). I viewed the register and everything was OK. 
- I entered a 2nd patient in the register (monthly number 2). I viewed the register and the monthly number for the first patient is missing (see screenshot). 
- I entered a 3rd patient in the register (monthly number 3). I viewed the register and the monthly number for the first patient is missing, and the monthly number for the 2nd patient now says "1" instead of "2" (see screenshot). 
- I entered a 4th patient in the register (monthly number 13789). I viewed the register and the monthly number for the first patient is missing, and the monthly number for the 2nd patient says "1" instead of "2", and the monthly number for the 3rd patient says "2" instead of "3".

![Entered 2nd patient](https://user-images.githubusercontent.com/9537700/98327774-37246c00-1fa9-11eb-9f55-7d7d3303d938.png)
![Entered 3rd patient - b](https://user-images.githubusercontent.com/9537700/98327779-38559900-1fa9-11eb-808d-02aeb85455a0.png)
![Entered 3rd patient - a](https://user-images.githubusercontent.com/9537700/98327781-3986c600-1fa9-11eb-997f-3fc09f52e49f.png)

**Comment by whpVishal** [comment]
This Bug has been fixed in latest build i shared.
