### ISSUE TITLE
Really long wait time to load data in register

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#352]
Demo APK (Nov 11 latest), when I log in as a user with some data (French language, username ekalwele, pw: kataki), and then go to the Prenatal (CPN) register, and click "View Register". Then I try to view data from Sept 2020. It takes a LONG time to load this data. I did the same for July 2020, etc. I have a black screen for some time, then it loads the data.

**Comment by whpVishal** [comment]
I made changes to the existing code and it is taking less time. It can't be reduced any more because of the redesigning take place every time we select any month.
The black screen will be not coming any more
