### ISSUE TITLE
Need option to only show numerical keyboard

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#43]
Currently, in the admin, the only way to show a numerical keyboard is to select the "Optional Unit Text" as the component type. However, this requires the admin to enter in units. 

There are times when we want a numerical keyboard WITHOUT units (monthly number, file number, etc). Please add a component type that is called "Number" in which when the user is on that screen, the keyboard defaults to the numerical keyboard.

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
What component type is it?  I was expecting to see a type "Number" as defined above.  I don't see any new options. 

<img width="937" alt="screen shot 2017-03-15 at 8 24 48 pm" src="https://cloud.githubusercontent.com/assets/9537700/23980531/758cf774-09bd-11e7-8201-0c0c12a434d5.png">
