### ISSUE TITLE
Component list not working

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#45]
Getting: "Unknown column 'a.name' in 'field list'" error 
http://103.225.41.0/ltfhcdynamic/admin/index.php?page=component&action=view
<img width="944" alt="screen shot 2017-03-01 at 9 31 21 pm" 
src="https://cloud.githubusercontent.com/assets/9537700/23494264/8e54349a-fec6-11e6-88d6-61c23c423aac.png">

**Comment by whppawan** [comment]
Done
