### ISSUE TITLE
Login page wordsmithing

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#51]
On the login screen, for French language, please change the following: 
"Choisissez la langue" should be "Choisir la langue"
"Se connecter" should be "Connecter"
"mot de passe" should be "Mot de passe" (just make the M capital)
"D'accord" should be "OK"

For Kiswahili, please change the following: 
"kuchagua lugha" should be "Chagua luga"
"Weka sahihi" should be "Ji unge"
"nywila" should be "Neno la Kificho"
"Sawa" should be "OK"
"Umesahau nywila?" should be "Je, Umesahau neno la kificho?"

**Comment by whppawan** [comment]
Done
