### ISSUE TITLE
Registration screen edits

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#55]
The following edits are needed on the registration screen: 
"First Name" should be "Health worker first name"
Next line is missing title. Should be: "Health worker last name"
Clinic id should be removed

![screenshot_2017-03-10-19-10-15](https://cloud.githubusercontent.com/assets/9537700/23820078/8b891e96-05c5-11e7-8a57-e7097e32c9f5.png)

**Comment by space-ravi** [comment]
Edits still needed: 
"Health worker first" should be "Health worker given name"
"Health worker last name" should be "Health worker family name"
Replace "Clinic Id" with "Health Clinic" (and make sure the field type accepts letters, currently clinic id is set to numbers)

The French and Swahili translations for the fields are in the attached spreadsheet.
[Registration fields translated.xlsx](https://github.com/kamal1978/LTFHC/files/866387/Registration.fields.translated.xlsx)

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
@whppawan This is incomplete. See my latest comment which has edits different than what you implemented.

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
@whppawan remaining issues: 
In French and Swahili, the given name and family name translations are not correct (see spreadsheet).

**Comment by whppawan** [comment]
In spreadsheet, the translation is of "Health worker first name" AND "Health worker last name". While it has been changed to "Health worker given name" AND "Health worker family name".
