### ISSUE TITLE
Disable internet at start of application

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#61]
Per a conversation with Kamal: Disabling internet/GPS/bluetooth when starting the application will help to conserve power. Internet should become active when upload button is pressed. 

Alternately - I can have the health worker put the tablet in airplane mode and enable it only when uploading the data.

**Comment by space-ravi** [comment]
@whppawan Seems like you resolved this issue. However, now I can't select a new language because the app cannot access the internet to get the data.

**Comment by space-ravi** [comment]
Keep WiFi on.

**Comment by whppawan** [comment]
Done
