### ISSUE TITLE
Some buttons don't have rounded corners

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#67]
Despite defining certain buttons as having rounded corners, some don't. Example: NO button on the Prenatal Referral screen: 

http://103.225.41.0/ltfhcdynamic/admin/index.php?page=component&search_screen_id=31&start=&action=edit&id=162

The button is not rounded when I make the button red. Please let me know what I need to do to fix this since this issue is happening on several slides.

**Comment by whppawan** [comment]
Done
