### ISSUE TITLE
Screens only showing up in English

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#71]
I selected French as the language and then logged in. The remaining screens starting from the "Prenatal Main Menu" show up in English. 

Same issue with Swahili.

**Comment by space-ravi** [comment]
Related issue - I logged out, changed my language to English. After logging in, the main menu screen is in Swahili. After clearing data, deleting app, and reinstalling, this part of the issue was resolved (original issue posted above still exists).

**Comment by whppawan** [comment]
Done
