### ISSUE TITLE
Not able to create account offline

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#78]
If I create an account while offline, and then try to log into that account, it does not work (after logging in, I just get a blank white screen). Using OS 4.4.2

Replication process: 
- Clear data off tablet
- Delete/reinstall app
- Turn WiFi off
- Create a new account
- Try to log in with account

This scenario is realistic since accounts will be created in remote areas where there is no internet.

**Comment by whppawan** [comment]
Clear data flushes all the data like ragister, health worker, all screens etc. So when you create an offline account and logged in. It dosen't find any screen to show. So after clearing the data the app needs internet for first login to get back all the screens.

**Comment by space-ravi** [comment]
Ravi to test process above but without clearing data.
