### ISSUE TITLE
Cannot log into existing accounts while offline

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#79]
If I freshly install the app, and try to log into an existing account, it does not recognize the existing account (using OS 4.4.2).

Replication process:
- Clear data off tablet
- Delete/reinstall app
- Turn WiFi off
- Log in with username: test, password: 123

Tablet message is "Wrong UserName and Password"

**Comment by space-ravi** [comment]
Can't work because tablet cannot magically know user credentials when it has been cleared.

**Comment by space-ravi** [comment]
@whppawan - Is there a way that when you download the app, you automatically download all the screens and existing user credentials?  That way the app won't take a long time to log in, and you can log into an existing account in an area without WiFi.

**Comment by whppawan** [comment]
Due to language selection option we have not given the feature to download screens. But if still you want to download the screen then we have to set 1 default language.

**Comment by space-ravi** [comment]
Can we download all languages?  If not, then download the French language as default please.

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Need to think through this and be very clear how to prevent an issue when setting up a user in a remote area. Talk through with Pawan: 

Scenario 1: 
- Download app onto HCW account on tablet
- No longer have WiFi
- Try to log in to app (first time) using existing credentials 
- Doesn't work!

Scenario 2: 
- Download app onto HCW account on tablet
- No longer have WiFi
- Try to create new credentials 
- Doesn't work!

**Comment by whppawan** [comment]
The app needs internet when it is being opened first time after installing or clearing the data.
