### ISSUE TITLE
First time log in takes a long time

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#80]
The first time an account logs in, it takes a very long time. In some cases, it times out. Is there something we can do to speed it up? In places with slow internet, I'm worried it will always time out.

**Comment by space-ravi** [comment]
Lowest priority high priority issue

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Great - I'm curious what you did?

**Comment by space-ravi** [comment]
Note to self: No action was taken here.
