### ISSUE TITLE
Register not providing value if French component names are used

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#81]
If a patient is recorded using the English language, and the report is viewed in French, the register does not provide the value. For example, in English the register looks good. In French, when the French component name is used, the monthly number is not there. This needs to work so that the health worker can view the register in any language and see the summary. 

English:
![screenshot_2017-03-18-20-23-09](https://cloud.githubusercontent.com/assets/9537700/24077874/e5253c4c-0c18-11e7-88b3-739fa942b5f0.png)

French: 
![screenshot_2017-03-18-20-23-28](https://cloud.githubusercontent.com/assets/9537700/24077878/ff960a52-0c18-11e7-877b-101c21f970e0.png)

**Comment by whppawan** [comment]
Done
