### ISSUE TITLE
Selecting row on register should take user to patient summary screen

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#82]
One primary use for the register is to be a way for the user to link to the patient data. When the user clicks on any part of the row containing a patient, the app should take the user to the patient summary screen for that particular patient.

**Comment by whppawan** [comment]
Done

**Comment by whppawan** [comment]
PLease upload the new version from play store.

**Comment by space-ravi** [comment]
Works on English version. Need to check in French and Swahili.

**Comment by space-ravi** [comment]
When I click on the patient with the name: Fghji Bhju, I go to the summary screen for a patient named Katie. 

![screenshot_2017-03-31-10-05-38](https://cloud.githubusercontent.com/assets/9537700/24560989/e398778c-15f9-11e7-8400-91928e48e1bd.png)

![screenshot_2017-03-31-10-05-48](https://cloud.githubusercontent.com/assets/9537700/24560992/e6e2e814-15f9-11e7-805a-0ed8167e6eb5.png)

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
@whppawan Exact issue is still persisting.
