### ISSUE TITLE
Register should scroll horizontally

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#83]
The register is going to have many, many columns. It needs to be able to scroll horizontally. Please show a maximum of 6 columns (each should be fixed and equal width) and have the rest be visible when the user scrolls the screen. (There should be a very visible horizontal scroll bar). 

![screenshot_2017-03-18-21-16-37](https://cloud.githubusercontent.com/assets/9537700/24078091/3fe5386a-0c20-11e7-9cb4-2e69e30d80e7.png)

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
Number of columns should be reduced (make columns wider)
