### ISSUE TITLE
Allowed to create new users with same username

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#89]
The app allows two users to have the same username. This will mess with our data analysis. The app should protect against this and not allow two users to have the same username. 

Error message if user tries to create an account with the same username as an existing account: 
"Sorry, that username is already taken, please enter another username."

**Comment by whppawan** [comment]
Done

**Comment by space-ravi** [comment]
@whppawan the text does not need the quotes in the alerts.

**Comment by whppawan** [comment]
Done
